import sys
import os


# ----------------------------------------------------------------------------------------------------------------------
# function for building executable with PyInstaller adding the data files needed (images, sounds)
def resource_path(relative_path):
    try:
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        base_path = sys._MEIPASS
    except AttributeError:
        base_path = os.path.abspath(".")

    return os.path.join(base_path, relative_path)


# asset urls -----------------------------------------------------------------------------------------------------------

# stan mage ------------------------------------------------------------------------------------------------------------
stan_down_url_1024_mage = resource_path('resources/art/character_art/player_character/default/mage/'
                                        'stan_down_1024_mage.png')
stan_down_url_mage = resource_path('resources/art/character_art/player_character/default/mage/'
                                   'stan_down_mage.png')
stan_down_url_1600_mage = resource_path('resources/art/character_art/player_character/default/mage/'
                                        'stan_down_1600_mage.png')
stan_left_url_1024_mage = resource_path('resources/art/character_art/player_character/default/mage/'
                                        'stan_left_1024_mage.png')
stan_left_url_mage = resource_path('resources/art/character_art/player_character/default/mage/'
                                   'stan_left_mage.png')
stan_left_url_1600_mage = resource_path('resources/art/character_art/player_character/default/mage/'
                                        'stan_left_1600_mage.png')
stan_right_url_1024_mage = resource_path('resources/art/character_art/player_character/default/mage/'
                                         'stan_right_1024_mage.png')
stan_right_url_mage = resource_path('resources/art/character_art/player_character/default/mage/'
                                    'stan_right_mage.png')
stan_right_url_1600_mage = resource_path('resources/art/character_art/player_character/default/mage/'
                                         'stan_right_1600_mage.png')
stan_up_url_1024_mage = resource_path('resources/art/character_art/player_character/default/mage/'
                                      'stan_up_1024_mage.png')
stan_up_url_mage = resource_path('resources/art/character_art/player_character/default/mage/'
                                 'stan_up_mage.png')
stan_up_url_1600_mage = resource_path('resources/art/character_art/player_character/default/mage/'
                                      'stan_up_1600_mage.png')
stan_battle_url_1024_mage = resource_path('resources/art/character_art/player_character/default/battle/mage/'
                                          'stan_battle_1024_mage.png')
stan_battle_url_mage = resource_path('resources/art/character_art/player_character/default/battle/mage/'
                                     'stan_battle_mage.png')
stan_battle_url_1600_mage = resource_path('resources/art/character_art/player_character/default/battle/mage/'
                                          'stan_battle_1600_mage.png')
stan_attack_url_1024_mage = resource_path('resources/art/character_art/player_character/default/battle/mage/'
                                          'stan_battle_attacking_1024_mage.png')
stan_attack_url_mage = resource_path('resources/art/character_art/player_character/default/battle/mage/'
                                     'stan_battle_attacking_mage.png')
stan_attack_url_1600_mage = resource_path('resources/art/character_art/player_character/default/battle/mage/'
                                          'stan_battle_attacking_1600_mage.png')

# stan fighter ---------------------------------------------------------------------------------------------------------
stan_down_url_1024_fighter = resource_path('resources/art/character_art/player_character/default/fighter/'
                                           'stan_down_1024_fighter.png')
stan_down_url_fighter = resource_path('resources/art/character_art/player_character/default/fighter/'
                                      'stan_down_fighter.png')
stan_down_url_1600_fighter = resource_path('resources/art/character_art/player_character/default/fighter/'
                                           'stan_down_1600_fighter.png')
stan_left_url_1024_fighter = resource_path('resources/art/character_art/player_character/default/fighter/'
                                           'stan_left_1024_fighter.png')
stan_left_url_fighter = resource_path('resources/art/character_art/player_character/default/fighter/'
                                      'stan_left_fighter.png')
stan_left_url_1600_fighter = resource_path('resources/art/character_art/player_character/default/fighter/'
                                           'stan_left_1600_fighter.png')
stan_right_url_1024_fighter = resource_path('resources/art/character_art/player_character/default/fighter/'
                                            'stan_right_1024_fighter.png')
stan_right_url_fighter = resource_path('resources/art/character_art/player_character/default/fighter/'
                                       'stan_right_fighter.png')
stan_right_url_1600_fighter = resource_path('resources/art/character_art/player_character/default/fighter/'
                                            'stan_right_1600_fighter.png')
stan_up_url_1024_fighter = resource_path('resources/art/character_art/player_character/default/fighter/'
                                         'stan_up_1024_fighter.png')
stan_up_url_fighter = resource_path('resources/art/character_art/player_character/default/fighter/stan_up_fighter.png')
stan_up_url_1600_fighter = resource_path('resources/art/character_art/player_character/default/fighter/'
                                         'stan_up_1600_fighter.png')
stan_battle_url_1024_fighter = resource_path('resources/art/character_art/player_character/default/battle/fighter/'
                                             'stan_battle_1024_fighter.png')
stan_battle_url_fighter = resource_path('resources/art/character_art/player_character/default/battle/fighter/'
                                        'stan_battle_fighter.png')
stan_battle_url_1600_fighter = resource_path('resources/art/character_art/player_character/default/battle/fighter/'
                                             'stan_battle_1600_fighter.png')
stan_attack_url_1024_fighter = resource_path('resources/art/character_art/player_character/default/battle/fighter/'
                                             'stan_battle_attacking_1024_fighter.png')
stan_attack_url_fighter = resource_path('resources/art/character_art/player_character/default/battle/fighter/'
                                        'stan_battle_attacking_fighter.png')
stan_attack_url_1600_fighter = resource_path('resources/art/character_art/player_character/default/battle/fighter/'
                                             'stan_battle_attacking_1600_fighter.png')

# stan scout -----------------------------------------------------------------------------------------------------------
stan_down_url_1024_scout = resource_path('resources/art/character_art/player_character/default/scout/'
                                         'stan_down_1024_scout.png')
stan_down_url_scout = resource_path('resources/art/character_art/player_character/default/scout/stan_down_scout.png')
stan_down_url_1600_scout = resource_path('resources/art/character_art/player_character/default/scout/'
                                         'stan_down_1600_scout.png')
stan_left_url_1024_scout = resource_path('resources/art/character_art/player_character/default/scout/'
                                         'stan_left_1024_scout.png')
stan_left_url_scout = resource_path('resources/art/character_art/player_character/default/scout/'
                                    'stan_left_scout.png')
stan_left_url_1600_scout = resource_path('resources/art/character_art/player_character/default/scout/'
                                         'stan_left_1600_scout.png')
stan_right_url_1024_scout = resource_path('resources/art/character_art/player_character/default/scout/'
                                          'stan_right_1024_scout.png')
stan_right_url_scout = resource_path('resources/art/character_art/player_character/default/scout/'
                                     'stan_right_scout.png')
stan_right_url_1600_scout = resource_path('resources/art/character_art/player_character/default/scout/'
                                          'stan_right_1600_scout.png')
stan_up_url_1024_scout = resource_path('resources/art/character_art/player_character/default/scout/'
                                       'stan_up_1024_scout.png')
stan_up_url_scout = resource_path('resources/art/character_art/player_character/default/scout/'
                                  'stan_up_scout.png')
stan_up_url_1600_scout = resource_path('resources/art/character_art/player_character/default/scout/'
                                       'stan_up_1600_scout.png')
stan_battle_url_1024_scout = resource_path('resources/art/character_art/player_character/default/battle/scout/'
                                           'stan_battle_1024_scout.png')
stan_battle_url_scout = resource_path('resources/art/character_art/player_character/default/battle/scout/'
                                      'stan_battle_scout.png')
stan_battle_url_1600_scout = resource_path('resources/art/character_art/player_character/default/battle/scout/'
                                           'stan_battle_1600_scout.png')
stan_attack_url_1024_scout = resource_path('resources/art/character_art/player_character/default/battle/scout/'
                                           'stan_battle_attacking_1024_scout.png')
stan_attack_url_scout = resource_path('resources/art/character_art/player_character/default/battle/scout/'
                                      'stan_battle_attacking_scout.png')
stan_attack_url_1600_scout = resource_path('resources/art/character_art/player_character/default/battle/scout/'
                                           'stan_battle_attacking_1600_scout.png')

amuna_shopkeeper_url = resource_path('resources/art/character_art/NPCs/shops/amuna_shopkeeper.png')

garan_url_1024 = resource_path('resources/art/character_art/NPCs/garan/garan_1024.png')
garan_url = resource_path('resources/art/character_art/NPCs/garan/garan.png')
garan_url_1600 = resource_path('resources/art/character_art/NPCs/garan/garan_1600.png')
garan_left_url_1024 = resource_path('resources/art/character_art/NPCs/garan/garan_left_1024.png')
garan_left_url = resource_path('resources/art/character_art/NPCs/garan/garan_left.png')
garan_left_url_1600 = resource_path('resources/art/character_art/NPCs/garan/garan_left_1600.png')
garan_right_url_1024 = resource_path('resources/art/character_art/NPCs/garan/garan_right_1024.png')
garan_right_url = resource_path('resources/art/character_art/NPCs/garan/garan_right.png')
garan_right_url_1600 = resource_path('resources/art/character_art/NPCs/garan/garan_right_1600.png')
garan_back_url_1024 = resource_path('resources/art/character_art/NPCs/garan/garan_back_1024.png')
garan_back_url = resource_path('resources/art/character_art/NPCs/garan/garan_back.png')
garan_back_url_1600 = resource_path('resources/art/character_art/NPCs/garan/garan_back_1600.png')

guard_url_1024 = resource_path('resources/art/character_art/NPCs/guards/guard_1024.png')
guard_url = resource_path('resources/art/character_art/NPCs/guards/guard.png')
guard_url_1600 = resource_path('resources/art/character_art/NPCs/guards/guard_1600.png')
guard_left_url_1024 = resource_path('resources/art/character_art/NPCs/guards/guard_left_1024.png')
guard_left_url = resource_path('resources/art/character_art/NPCs/guards/guard_left.png')
guard_left_url_1600 = resource_path('resources/art/character_art/NPCs/guards/guard_left_1600.png')
guard_right_url_1024 = resource_path('resources/art/character_art/NPCs/guards/guard_right_1024.png')
guard_right_url = resource_path('resources/art/character_art/NPCs/guards/guard_right.png')
guard_right_url_1600 = resource_path('resources/art/character_art/NPCs/guards/guard_right_1600.png')
guard_back_url_1024 = resource_path('resources/art/character_art/NPCs/guards/guard_back_1024.png')
guard_back_url = resource_path('resources/art/character_art/NPCs/guards/guard_back.png')
guard_back_url_1600 = resource_path('resources/art/character_art/NPCs/guards/guard_back_1600.png')

maurelle_url_1024 = resource_path('resources/art/character_art/NPCs/maurelle/maurelle_1024.png')
maurelle_url = resource_path('resources/art/character_art/NPCs/maurelle/maurelle.png')
maurelle_url_1600 = resource_path('resources/art/character_art/NPCs/maurelle/maurelle_1600.png')
maurelle_left_url_1024 = resource_path('resources/art/character_art/NPCs/maurelle/maurelle_left_1024.png')
maurelle_left_url = resource_path('resources/art/character_art/NPCs/maurelle/maurelle_left.png')
maurelle_left_url_1600 = resource_path('resources/art/character_art/NPCs/maurelle/maurelle_left_1600.png')
maurelle_right_url_1024 = resource_path('resources/art/character_art/NPCs/maurelle/maurelle_right_1024.png')
maurelle_right_url = resource_path('resources/art/character_art/NPCs/maurelle/maurelle_right.png')
maurelle_right_url_1600 = resource_path('resources/art/character_art/NPCs/maurelle/maurelle_right_1600.png')
maurelle_back_url_1024 = resource_path('resources/art/character_art/NPCs/maurelle/maurelle_back_1024.png')
maurelle_back_url = resource_path('resources/art/character_art/NPCs/maurelle/maurelle_back.png')
maurelle_back_url_1600 = resource_path('resources/art/character_art/NPCs/maurelle/maurelle_back_1600.png')

snake_url_1024 = resource_path('resources/art/enemy_art/snake_1024.png')
snake_url = resource_path('resources/art/enemy_art/snake.png')
snake_url_1600 = resource_path('resources/art/enemy_art/snake_1600.png')
ghoul_url_1024 = resource_path('resources/art/enemy_art/ghoul_1024.png')
ghoul_url = resource_path('resources/art/enemy_art/ghoul.png')
ghoul_url_1600 = resource_path('resources/art/enemy_art/ghoul_1600.png')
snake_battle_url_1024 = resource_path('resources/art/enemy_art/battle/snake_battle_1024.png')
snake_battle_url = resource_path('resources/art/enemy_art/battle/snake_battle.png')
snake_battle_url_1600 = resource_path('resources/art/enemy_art/battle/snake_battle_1600.png')
snake_attack_url_1024 = resource_path('resources/art/enemy_art/battle/snake_battle_attacking_1024.png')
snake_attack_url = resource_path('resources/art/enemy_art/battle/snake_battle_attacking.png')
snake_attack_url_1600 = resource_path('resources/art/enemy_art/battle/snake_battle_attacking_1600.png')
ghoul_battle_url_1024 = resource_path('resources/art/enemy_art/battle/ghoul_battle_1024.png')
ghoul_battle_url = resource_path('resources/art/enemy_art/battle/ghoul_battle.png')
ghoul_battle_url_1600 = resource_path('resources/art/enemy_art/battle/ghoul_battle_1600.png')
ghoul_attack_url_1024 = resource_path('resources/art/enemy_art/battle/ghoul_battle_attacking_1024.png')
ghoul_attack_url = resource_path('resources/art/enemy_art/battle/ghoul_battle_attacking.png')
ghoul_attack_url_1600 = resource_path('resources/art/enemy_art/battle/ghoul_battle_attacking_1600.png')

seldon_bg_screen_url_1024 = resource_path('resources/art/environment_art/background_textures/seldon_district_1024.png')
seldon_bg_screen_url = resource_path('resources/art/environment_art/background_textures/seldon_district.png')
seldon_bg_screen_url_1600 = resource_path('resources/art/environment_art/background_textures/seldon_district_1600.png')
seldon_battle_screen_url_1024 = resource_path('resources/art/environment_art/background_textures/'
                                              'seldon_battle_screen_1024.png')
seldon_battle_screen_url = resource_path('resources/art/environment_art/background_textures/seldon_battle_screen.png')
seldon_battle_screen_url_1600 = resource_path('resources/art/environment_art/background_textures/'
                                              'seldon_battle_screen_1600.png')
seldon_shop_screen_url_1024 = resource_path('resources/art/environment_art/background_textures/seldon_shop_1024.png')
seldon_shop_screen_url = resource_path('resources/art/environment_art/background_textures/seldon_shop.png')
seldon_shop_screen_url_1600 = resource_path('resources/art/environment_art/background_textures/seldon_shop_1600.png')
seldon_inn_screen_url_1024 = resource_path('resources/art/environment_art/background_textures/seldon_inn_1024.png')
seldon_inn_screen_url = resource_path('resources/art/environment_art/background_textures/seldon_inn.png')
seldon_inn_screen_url_1600 = resource_path('resources/art/environment_art/background_textures/seldon_inn_1600.png')
seldon_academia_screen_url_1024 = resource_path('resources/art/environment_art/background_textures/'
                                                'seldon_academia_1024.png')
seldon_academia_screen_url = resource_path('resources/art/environment_art/background_textures/seldon_academia.png')
seldon_academia_screen_url_1600 = resource_path('resources/art/environment_art/background_textures/'
                                                'seldon_academia_1600.png')

seldon_academia_url_1024 = resource_path('resources/art/environment_art/buildings/amuna_building_academia_1024.png')
seldon_academia_url = resource_path('resources/art/environment_art/buildings/amuna_building_academia.png')
seldon_academia_url_1600 = resource_path('resources/art/environment_art/buildings/amuna_building_academia_1600.png')
seldon_inn_url_1024 = resource_path('resources/art/environment_art/buildings/amuna_building_inn_1024.png')
seldon_inn_url = resource_path('resources/art/environment_art/buildings/amuna_building_inn.png')
seldon_inn_url_1600 = resource_path('resources/art/environment_art/buildings/amuna_building_inn_1600.png')
seldon_shop_url_1024 = resource_path('resources/art/environment_art/buildings/amuna_building_shop_1024.png')
seldon_shop_url = resource_path('resources/art/environment_art/buildings/amuna_building_shop.png')
seldon_shop_url_1600 = resource_path('resources/art/environment_art/buildings/amuna_building_shop_1600.png')

pine_tree_url_1024 = resource_path('resources/art/environment_art/pine_tree_1024.png')
pine_tree_url = resource_path('resources/art/environment_art/pine_tree.png')
pine_tree_url_1600 = resource_path('resources/art/environment_art/pine_tree_1600.png')
seldon_grass_url_1024 = resource_path('resources/art/environment_art/seldon_grass_1024.png')
seldon_grass_url = resource_path('resources/art/environment_art/seldon_grass.png')
seldon_grass_url_1600 = resource_path('resources/art/environment_art/seldon_grass_1600.png')
seldon_flower_url_1024 = resource_path('resources/art/environment_art/seldon_flower_1024.png')
seldon_flower_url = resource_path('resources/art/environment_art/seldon_flower.png')
seldon_flower_url_1600 = resource_path('resources/art/environment_art/seldon_flower_1600.png')

health_pot_url_1024 = resource_path('resources/art/item_art/health_potion_1024.png')
health_pot_url = resource_path('resources/art/item_art/health_potion.png')
health_pot_url_1600 = resource_path('resources/art/item_art/health_potion_1600.png')
energy_pot_url_1024 = resource_path('resources/art/item_art/energy_potion_1024.png')
energy_pot_url = resource_path('resources/art/item_art/energy_potion.png')
energy_pot_url_1600 = resource_path('resources/art/item_art/energy_potion_1600.png')
shiny_rock_url_1024 = resource_path('resources/art/item_art/shiny_rock_1024.png')
shiny_rock_url = resource_path('resources/art/item_art/shiny_rock.png')
shiny_rock_url_1600 = resource_path('resources/art/item_art/shiny_rock_1600.png')
bone_dust_url_1024 = resource_path('resources/art/item_art/bone_dust_1024.png')
bone_dust_url = resource_path('resources/art/item_art/bone_dust.png')
bone_dust_url_1600 = resource_path('resources/art/item_art/bone_dust_1600.png')
temp_item_url_1024 = resource_path('resources/art/item_art/temp_item_1024.png')
temp_item_url = resource_path('resources/art/item_art/temp_item.png')
temp_item_url_1600 = resource_path('resources/art/item_art/temp_item_1600.png')

basic_staff_url_1024 = resource_path('resources/art/item_art/equipment/basic_staff_1024.png')
basic_staff_url = resource_path('resources/art/item_art/equipment/basic_staff.png')
basic_staff_url_1600 = resource_path('resources/art/item_art/equipment/basic_staff_1600.png')
basic_sword_url_1024 = resource_path('resources/art/item_art/equipment/basic_sword_1024.png')
basic_sword_url = resource_path('resources/art/item_art/equipment/basic_sword.png')
basic_sword_url_1600 = resource_path('resources/art/item_art/equipment/basic_sword_1600.png')
basic_bow_url_1024 = resource_path('resources/art/item_art/equipment/basic_bow_1024.png')
basic_bow_url = resource_path('resources/art/item_art/equipment/basic_bow.png')
basic_bow_url_1600 = resource_path('resources/art/item_art/equipment/basic_bow_1600.png')

basic_robes_url_1024 = resource_path('resources/art/item_art/equipment/basic_robes_1024.png')
basic_robes_url = resource_path('resources/art/item_art/equipment/basic_robes.png')
basic_robes_url_1600 = resource_path('resources/art/item_art/equipment/basic_robes_1600.png')
basic_armor_url_1024 = resource_path('resources/art/item_art/equipment/basic_armor_1024.png')
basic_armor_url = resource_path('resources/art/item_art/equipment/basic_armor.png')
basic_armor_url_1600 = resource_path('resources/art/item_art/equipment/basic_armor_1600.png')
basic_tunic_url_1024 = resource_path('resources/art/item_art/equipment/basic_tunic_1024.png')
basic_tunic_url = resource_path('resources/art/item_art/equipment/basic_tunic.png')
basic_tunic_url_1600 = resource_path('resources/art/item_art/equipment/basic_tunic_1600.png')

game_over_screen_url_1024 = resource_path('resources/art/screens/game_over_1024.png')
game_over_screen_url = resource_path('resources/art/screens/game_over.png')
game_over_screen_url_1600 = resource_path('resources/art/screens/game_over_1600.png')
start_screen_url_1024 = resource_path('resources/art/screens/start_screen_1024.png')
start_screen_url = resource_path('resources/art/screens/start_screen.png')
start_screen_url_1600 = resource_path('resources/art/screens/start_screen_1600.png')
nera_sleep_screen_url_1024 = resource_path('resources/art/screens/nera_sleep_screen_1024.png')
nera_sleep_screen_url = resource_path('resources/art/screens/nera_sleep_screen.png')
nera_sleep_screen_url_1600 = resource_path('resources/art/screens/nera_sleep_screen_1600.png')

character_sheet_url_1024 = resource_path('resources/art/ui_elements/character_sheet_1024.png')
character_sheet_url = resource_path('resources/art/ui_elements/character_sheet.png')
character_sheet_url_1600 = resource_path('resources/art/ui_elements/character_sheet_1600.png')
journal_url_1024 = resource_path('resources/art/ui_elements/journal_1024.png')
journal_url = resource_path('resources/art/ui_elements/journal.png')
journal_url_1600 = resource_path('resources/art/ui_elements/journal_1600.png')
level_up_url_1024 = resource_path('resources/art/ui_elements/level_up_1024.png')
level_up_url = resource_path('resources/art/ui_elements/level_up.png')
level_up_url_1600 = resource_path('resources/art/ui_elements/level_up_1600.png')
bar_backdrop_url = resource_path('resources/art/ui_elements/status_bar_backdrop.png')
enemy_bar_backdrop_url = resource_path('resources/art/ui_elements/enemy_status_bar_backdrop.png')
buy_inventory_url_1024 = resource_path('resources/art/ui_elements/buy_inventory_1024.png')
buy_inventory_url = resource_path('resources/art/ui_elements/buy_inventory.png')
buy_inventory_url_1600 = resource_path('resources/art/ui_elements/buy_inventory_1600.png')
inventory_url = resource_path('resources/art/ui_elements/inventory.png')
message_box_url_1024 = resource_path('resources/art/ui_elements/message_box_1024.png')
message_box_url = resource_path('resources/art/ui_elements/message_box.png')
message_box_url_1600 = resource_path('resources/art/ui_elements/message_box_1600.png')
mage_book_url_1024 = resource_path('resources/art/ui_elements/mage_book_1024.png')
mage_book_url = resource_path('resources/art/ui_elements/mage_book.png')
mage_book_url_1600 = resource_path('resources/art/ui_elements/mage_book_1600.png')
fighter_book_url_1024 = resource_path('resources/art/ui_elements/fighter_book_1024.png')
fighter_book_url = resource_path('resources/art/ui_elements/fighter_book.png')
fighter_book_url_1600 = resource_path('resources/art/ui_elements/fighter_book_1600.png')
scout_book_url_1024 = resource_path('resources/art/ui_elements/scout_book_1024.png')
scout_book_url = resource_path('resources/art/ui_elements/scout_book.png')
scout_book_url_1600 = resource_path('resources/art/ui_elements/scout_book_1600.png')
enemy_status_url_1024 = resource_path('resources/art/ui_elements/status/enemy_status_backdrop_1024.png')
enemy_status_url = resource_path('resources/art/ui_elements/status/enemy_status_backdrop.png')
enemy_status_url_1600 = resource_path('resources/art/ui_elements/status/enemy_status_backdrop_1600.png')
welcome_image_url_1024 = resource_path('resources/art/ui_elements/notifications/welcome_1024.png')
welcome_image_url = resource_path('resources/art/ui_elements/notifications/welcome.png')
welcome_image_url_1600 = resource_path('resources/art/ui_elements/notifications/welcome_1600.png')
character_button_url_1024 = resource_path('resources/art/ui_elements/buttons/character_1024.png')
character_button_url = resource_path('resources/art/ui_elements/buttons/character.png')
character_button_url_1600 = resource_path('resources/art/ui_elements/buttons/character_1600.png')
continue_button_url_1024 = resource_path('resources/art/ui_elements/buttons/game_over_screen/continue_button_1024.png')
continue_button_url = resource_path('resources/art/ui_elements/buttons/game_over_screen/continue_button.png')
continue_button_url_1600 = resource_path('resources/art/ui_elements/buttons/game_over_screen/continue_button_1600.png')
journal_button_url_1024 = resource_path('resources/art/ui_elements/buttons/journal_1024.png')
journal_button_url = resource_path('resources/art/ui_elements/buttons/journal.png')
journal_button_url_1600 = resource_path('resources/art/ui_elements/buttons/journal_1600.png')
buy_button_url_1024 = resource_path('resources/art/ui_elements/buttons/shop/buy_1024.png')
buy_button_url = resource_path('resources/art/ui_elements/buttons/shop/buy.png')
buy_button_url_1600 = resource_path('resources/art/ui_elements/buttons/shop/buy_1600.png')
leave_button_url_1024 = resource_path('resources/art/ui_elements/buttons/shop/leave_1024.png')
leave_button_url = resource_path('resources/art/ui_elements/buttons/shop/leave.png')
leave_button_url_1600 = resource_path('resources/art/ui_elements/buttons/shop/leave_1600.png')
rest_button_url_1024 = resource_path('resources/art/ui_elements/buttons/inn/rest_1024.png')
rest_button_url = resource_path('resources/art/ui_elements/buttons/inn/rest.png')
rest_button_url_1600 = resource_path('resources/art/ui_elements/buttons/inn/rest_1600.png')
learn_button_url_1024 = resource_path('resources/art/ui_elements/buttons/academia/learn_1024.png')
learn_button_url = resource_path('resources/art/ui_elements/buttons/academia/learn.png')
learn_button_url_1600 = resource_path('resources/art/ui_elements/buttons/academia/learn_1600.png')
skill_learn_button_url_1024 = resource_path('resources/art/ui_elements/buttons/academia/skill_learn_1024.png')
skill_learn_button_url = resource_path('resources/art/ui_elements/buttons/academia/skill_learn.png')
skill_learn_button_url_1600 = resource_path('resources/art/ui_elements/buttons/academia/skill_learn_1600.png')
unstuck_button_url_1024 = resource_path('resources/art/ui_elements/buttons/unstuck_1024.png')
unstuck_button_url = resource_path('resources/art/ui_elements/buttons/unstuck.png')
unstuck_button_url_1600 = resource_path('resources/art/ui_elements/buttons/unstuck_1600.png')
close_button_url_1024 = resource_path('resources/art/ui_elements/buttons/close.png')
close_button_url = resource_path('resources/art/ui_elements/buttons/close.png')
close_button_url_1600 = resource_path('resources/art/ui_elements/buttons/close.png')
knowledge_window_url_1024 = resource_path('resources/art/ui_elements/buttons/academia/knowledge_1024.png')
knowledge_window_url = resource_path('resources/art/ui_elements/buttons/academia/knowledge.png')
knowledge_window_url_1600 = resource_path('resources/art/ui_elements/buttons/academia/knowledge_1600.png')
skill_bar_url_1024 = resource_path('resources/art/ui_elements/buttons/battle/skill_bar_1024.png')
skill_bar_url = resource_path('resources/art/ui_elements/buttons/battle/skill_bar.png')
skill_bar_url_1600 = resource_path('resources/art/ui_elements/buttons/battle/skill_bar_1600.png')
mage_attack_button_url_1024 = resource_path('resources/art/ui_elements/buttons/battle/mage/mage_attack_1024.png')
mage_attack_button_url = resource_path('resources/art/ui_elements/buttons/battle/mage/mage_attack.png')
mage_attack_button_url_1600 = resource_path('resources/art/ui_elements/buttons/battle/mage/mage_attack_1600.png')
fighter_attack_button_url_1024 = resource_path('resources/art/ui_elements/buttons/battle/fighter/fighter_attack_1024'
                                               '.png')
fighter_attack_button_url = resource_path('resources/art/ui_elements/buttons/battle/fighter/fighter_attack.png')
fighter_attack_button_url_1600 = resource_path('resources/art/ui_elements/buttons/battle/fighter/fighter_attack_1600'
                                               '.png')
scout_attack_button_url_1024 = resource_path('resources/art/ui_elements/buttons/battle/scout/scout_attack_1024.png')
scout_attack_button_url = resource_path('resources/art/ui_elements/buttons/battle/scout/scout_attack.png')
scout_attack_button_url_1600 = resource_path('resources/art/ui_elements/buttons/battle/scout/scout_attack_1600.png')
barrier_button_url_1024 = resource_path('resources/art/ui_elements/buttons/battle/mage/barrier_1024.png')
barrier_button_url = resource_path('resources/art/ui_elements/buttons/battle/mage/barrier.png')
barrier_button_url_1600 = resource_path('resources/art/ui_elements/buttons/battle/mage/barrier_1600.png')
hard_strike_button_url_1024 = resource_path('resources/art/ui_elements/buttons/battle/fighter/hard_strike_1024.png')
hard_strike_button_url = resource_path('resources/art/ui_elements/buttons/battle/fighter/hard_strike.png')
hard_strike_button_url_1600 = resource_path('resources/art/ui_elements/buttons/battle/fighter/hard_strike_1600.png')
sharp_sense_button_url_1024 = resource_path('resources/art/ui_elements/buttons/battle/scout/sharp_sense_1024.png')
sharp_sense_button_url = resource_path('resources/art/ui_elements/buttons/battle/scout/sharp_sense.png')
sharp_sense_button_url_1600 = resource_path('resources/art/ui_elements/buttons/battle/scout/sharp_sense_1600.png')

start_button_url_1024 = resource_path('resources/art/ui_elements/buttons/start_screen/start_button_1024.png')
start_button_url = resource_path('resources/art/ui_elements/buttons/start_screen/start_button.png')
start_button_url_1600 = resource_path('resources/art/ui_elements/buttons/start_screen/start_button_1600.png')
s1024_x_576_button_url_1024 = resource_path('resources/art/ui_elements/buttons/start_screen/1024x576_button_1024.png')
s1024_x_576_button_url = resource_path('resources/art/ui_elements/buttons/start_screen/1024x576_button.png')
s1024_x_576_button_url_1600 = resource_path('resources/art/ui_elements/buttons/start_screen/1024x576_button_1600.png')
s1280_x_720_button_url_1024 = resource_path('resources/art/ui_elements/buttons/start_screen/1280x720_button_1024.png')
s1280_x_720_button_url = resource_path('resources/art/ui_elements/buttons/start_screen/1280x720_button.png')
s1280_x_720_button_url_1600 = resource_path('resources/art/ui_elements/buttons/start_screen/1280x720_button_1600.png')
s1600_x_900_button_url_1024 = resource_path('resources/art/ui_elements/buttons/start_screen/1600x900_button_1024.png')
s1600_x_900_button_url = resource_path('resources/art/ui_elements/buttons/start_screen/1600x900_button.png')
s1600_x_900_button_url_1600 = resource_path('resources/art/ui_elements/buttons/start_screen/1600x900_button_1600.png')

health_100_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_100.png')
health_99_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_99.png')
health_98_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_98.png')
health_97_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_97.png')
health_96_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_96.png')
health_95_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_95.png')
health_94_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_94.png')
health_93_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_93.png')
health_92_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_92.png')
health_91_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_91.png')
health_90_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_90.png')
health_89_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_89.png')
health_88_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_88.png')
health_87_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_87.png')
health_86_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_86.png')
health_85_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_85.png')
health_84_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_84.png')
health_83_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_83.png')
health_82_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_82.png')
health_81_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_81.png')
health_80_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_80.png')
health_79_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_79.png')
health_78_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_78.png')
health_77_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_77.png')
health_76_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_76.png')
health_75_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_75.png')
health_74_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_74.png')
health_73_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_73.png')
health_72_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_72.png')
health_71_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_71.png')
health_70_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_70.png')
health_69_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_69.png')
health_68_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_68.png')
health_67_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_67.png')
health_66_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_66.png')
health_65_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_65.png')
health_64_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_64.png')
health_63_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_63.png')
health_62_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_62.png')
health_61_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_61.png')
health_60_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_60.png')
health_59_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_59.png')
health_58_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_58.png')
health_57_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_57.png')
health_56_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_56.png')
health_55_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_55.png')
health_54_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_54.png')
health_53_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_53.png')
health_52_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_52.png')
health_51_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_51.png')
health_50_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_50.png')
health_49_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_49.png')
health_48_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_48.png')
health_47_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_47.png')
health_46_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_46.png')
health_45_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_45.png')
health_44_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_44.png')
health_43_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_43.png')
health_42_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_42.png')
health_41_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_41.png')
health_40_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_40.png')
health_39_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_39.png')
health_38_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_38.png')
health_37_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_37.png')
health_36_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_36.png')
health_35_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_35.png')
health_34_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_34.png')
health_33_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_33.png')
health_32_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_32.png')
health_31_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_31.png')
health_30_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_30.png')
health_29_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_29.png')
health_28_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_28.png')
health_27_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_27.png')
health_26_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_26.png')
health_25_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_25.png')
health_24_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_24.png')
health_23_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_23.png')
health_22_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_22.png')
health_21_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_21.png')
health_20_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_20.png')
health_19_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_19.png')
health_18_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_18.png')
health_17_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_17.png')
health_16_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_16.png')
health_15_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_15.png')
health_14_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_14.png')
health_13_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_13.png')
health_12_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_12.png')
health_11_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_11.png')
health_10_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_10.png')
health_9_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_9.png')
health_8_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_8.png')
health_7_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_7.png')
health_6_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_6.png')
health_5_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_5.png')
health_4_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_4.png')
health_3_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_3.png')
health_2_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_2.png')
health_1_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_1.png')
health_0_url = resource_path('resources/art/ui_elements/bars/health/hp_bar_0.png')

energy_100_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_100.png')
energy_99_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_99.png')
energy_98_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_98.png')
energy_97_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_97.png')
energy_96_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_96.png')
energy_95_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_95.png')
energy_94_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_94.png')
energy_93_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_93.png')
energy_92_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_92.png')
energy_91_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_91.png')
energy_90_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_90.png')
energy_89_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_89.png')
energy_88_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_88.png')
energy_87_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_87.png')
energy_86_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_86.png')
energy_85_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_85.png')
energy_84_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_84.png')
energy_83_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_83.png')
energy_82_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_82.png')
energy_81_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_81.png')
energy_80_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_80.png')
energy_79_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_79.png')
energy_78_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_78.png')
energy_77_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_77.png')
energy_76_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_76.png')
energy_75_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_75.png')
energy_74_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_74.png')
energy_73_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_73.png')
energy_72_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_72.png')
energy_71_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_71.png')
energy_70_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_70.png')
energy_69_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_69.png')
energy_68_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_68.png')
energy_67_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_67.png')
energy_66_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_66.png')
energy_65_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_65.png')
energy_64_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_64.png')
energy_63_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_63.png')
energy_62_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_62.png')
energy_61_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_61.png')
energy_60_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_60.png')
energy_59_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_59.png')
energy_58_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_58.png')
energy_57_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_57.png')
energy_56_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_56.png')
energy_55_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_55.png')
energy_54_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_54.png')
energy_53_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_53.png')
energy_52_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_52.png')
energy_51_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_51.png')
energy_50_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_50.png')
energy_49_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_49.png')
energy_48_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_48.png')
energy_47_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_47.png')
energy_46_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_46.png')
energy_45_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_45.png')
energy_44_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_44.png')
energy_43_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_43.png')
energy_42_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_42.png')
energy_41_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_41.png')
energy_40_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_40.png')
energy_39_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_39.png')
energy_38_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_38.png')
energy_37_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_37.png')
energy_36_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_36.png')
energy_35_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_35.png')
energy_34_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_34.png')
energy_33_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_33.png')
energy_32_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_32.png')
energy_31_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_31.png')
energy_30_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_30.png')
energy_29_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_29.png')
energy_28_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_28.png')
energy_27_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_27.png')
energy_26_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_26.png')
energy_25_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_25.png')
energy_24_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_24.png')
energy_23_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_23.png')
energy_22_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_22.png')
energy_21_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_21.png')
energy_20_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_20.png')
energy_19_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_19.png')
energy_18_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_18.png')
energy_17_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_17.png')
energy_16_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_16.png')
energy_15_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_15.png')
energy_14_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_14.png')
energy_13_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_13.png')
energy_12_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_12.png')
energy_11_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_11.png')
energy_10_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_10.png')
energy_9_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_9.png')
energy_8_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_8.png')
energy_7_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_7.png')
energy_6_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_6.png')
energy_5_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_5.png')
energy_4_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_4.png')
energy_3_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_3.png')
energy_2_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_2.png')
energy_1_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_1.png')
energy_0_url = resource_path('resources/art/ui_elements/bars/energy/en_bar_0.png')

xp_100_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_100.png')
xp_99_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_99.png')
xp_98_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_98.png')
xp_97_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_97.png')
xp_96_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_96.png')
xp_95_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_95.png')
xp_94_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_94.png')
xp_93_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_93.png')
xp_92_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_92.png')
xp_91_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_91.png')
xp_90_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_90.png')
xp_89_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_89.png')
xp_88_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_88.png')
xp_87_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_87.png')
xp_86_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_86.png')
xp_85_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_85.png')
xp_84_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_84.png')
xp_83_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_83.png')
xp_82_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_82.png')
xp_81_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_81.png')
xp_80_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_80.png')
xp_79_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_79.png')
xp_78_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_78.png')
xp_77_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_77.png')
xp_76_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_76.png')
xp_75_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_75.png')
xp_74_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_74.png')
xp_73_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_73.png')
xp_72_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_72.png')
xp_71_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_71.png')
xp_70_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_70.png')
xp_69_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_69.png')
xp_68_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_68.png')
xp_67_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_67.png')
xp_66_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_66.png')
xp_65_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_65.png')
xp_64_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_64.png')
xp_63_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_63.png')
xp_62_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_62.png')
xp_61_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_61.png')
xp_60_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_60.png')
xp_59_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_59.png')
xp_58_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_58.png')
xp_57_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_57.png')
xp_56_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_56.png')
xp_55_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_55.png')
xp_54_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_54.png')
xp_53_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_53.png')
xp_52_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_52.png')
xp_51_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_51.png')
xp_50_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_50.png')
xp_49_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_49.png')
xp_48_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_48.png')
xp_47_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_47.png')
xp_46_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_46.png')
xp_45_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_45.png')
xp_44_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_44.png')
xp_43_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_43.png')
xp_42_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_42.png')
xp_41_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_41.png')
xp_40_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_40.png')
xp_39_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_39.png')
xp_38_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_38.png')
xp_37_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_37.png')
xp_36_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_36.png')
xp_35_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_35.png')
xp_34_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_34.png')
xp_33_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_33.png')
xp_32_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_32.png')
xp_31_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_31.png')
xp_30_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_30.png')
xp_29_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_29.png')
xp_28_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_28.png')
xp_27_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_27.png')
xp_26_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_26.png')
xp_25_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_25.png')
xp_24_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_24.png')
xp_23_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_23.png')
xp_22_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_22.png')
xp_21_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_21.png')
xp_20_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_20.png')
xp_19_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_19.png')
xp_18_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_18.png')
xp_17_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_17.png')
xp_16_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_16.png')
xp_15_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_15.png')
xp_14_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_14.png')
xp_13_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_13.png')
xp_12_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_12.png')
xp_11_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_11.png')
xp_10_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_10.png')
xp_9_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_9.png')
xp_8_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_8.png')
xp_7_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_7.png')
xp_6_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_6.png')
xp_5_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_5.png')
xp_4_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_4.png')
xp_3_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_3.png')
xp_2_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_2.png')
xp_1_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_1.png')
xp_0_url = resource_path('resources/art/ui_elements/bars/xp/xp_bar_0.png')

cat_url = resource_path('resources/art/critter_art/cat.png')

quest_logs_url_1024 = resource_path('resources/art/quest_items/logs_1024.png')
quest_logs_url = resource_path('resources/art/quest_items/logs.png')
quest_logs_url_1600 = resource_path('resources/art/quest_items/logs_1600.png')
