import os
import sys
import pygame

pygame.init()
pygame.display.set_caption("Project Eterna")
screen = pygame.display.set_mode((1280, 720), pygame.RESIZABLE)


# function for building executable with PyInstaller adding the data files needed (images, sounds)
def resource_path(relative_path):
    """ Get absolute path to resource, works for dev and for PyInstaller """
    base_path = getattr(sys, '_MEIPASS', os.path.dirname(os.path.abspath(__file__)))
    return os.path.join(base_path, relative_path)


def sprite_sheet(size, file, posit=(0, 0)):
    len_sprt_x, len_sprt_y = size  # sprite size
    sprt_rect_x, sprt_rect_y = posit  # first sprite on sheet

    sheet = pygame.image.load(file).convert_alpha()  # Load the sheet
    sheet.set_colorkey((255, 255, 255))
    sheet_rect = sheet.get_rect()
    sprites = []

    for i in range(0, sheet_rect.height, size[1]):  # rows
        for j in range(0, sheet_rect.width, size[0]):  # columns
            sheet.set_clip(pygame.Rect(sprt_rect_x, sprt_rect_y, len_sprt_x, len_sprt_y))  # find sprite
            sprite = sheet.subsurface(sheet.get_clip())  # grab sprite
            sprites.append(sprite)
            sprt_rect_x += len_sprt_x

        sprt_rect_y += len_sprt_y
        sprt_rect_x = 0

    return sprites


# non sprite sheets ----------------------------------------------------------------------------------------------------
a_char_screen = pygame.image.load(resource_path('resources/art/screen_amuna_character_select.png')).convert_alpha()
n_char_screen = pygame.image.load(resource_path('resources/art/screen_nuldar_character_select.png')).convert_alpha()
s_char_screen = pygame.image.load(resource_path('resources/art/screen_sorae_character_select.png')).convert_alpha()
nascent_grove_screen = pygame.image.load(resource_path('resources/art/bg_nascent_grove.png')).convert_alpha()
stardust_cove_screen = pygame.image.load(resource_path('resources/art/bg_stardust_post.png')).convert_alpha()
stardust_post_screen = pygame.image.load(resource_path('resources/art/bg_stardust_inn.png')).convert_alpha()
seldon_bg_screen = pygame.image.load(resource_path('resources/art/bg_seldon_district.png')).convert_alpha()
korlok_bg_screen = pygame.image.load(resource_path('resources/art/bg_korlok_district.png')).convert_alpha()
seldon_battle_screen = pygame.image.load(resource_path('resources/art/bg_seldon_battle_screen.png')).convert_alpha()
seldon_shop_screen = pygame.image.load(resource_path('resources/art/bg_seldon_shop.png')).convert_alpha()
seldon_inn_screen = pygame.image.load(resource_path('resources/art/bg_seldon_inn.png')).convert_alpha()
seldon_academia_screen = pygame.image.load(resource_path('resources/art/bg_seldon_academia.png')).convert_alpha()
seldon_hearth_screen = pygame.image.load(resource_path('resources/art/screen_seldon_hearth.png')).convert_alpha()
game_over_screen = pygame.image.load(resource_path('resources/art/screen_game_over.png')).convert_alpha()
start_screen = pygame.image.load(resource_path('resources/art/screen_start.png')).convert_alpha()
nera_sleep_screen = pygame.image.load(resource_path('resources/art/screen_nera_sleep.png')).convert_alpha()
bar_backdrop = pygame.image.load(resource_path('resources/art/overlay_status_bar_backdrop.png')).convert_alpha()
enemy_status = pygame.image.load(resource_path('resources/art/overlay_enemy_status_backdrop.png')).convert_alpha()
enemy_bar_backdrop = pygame.image.load(resource_path('resources/art/overlay_enemy_status_bar.png')).convert_alpha()
buy_inventory = pygame.image.load(resource_path('resources/art/overlay_buy_inventory.png')).convert_alpha()
message_box = pygame.image.load(resource_path('resources/art/overlay_message_box.png')).convert_alpha()
pine_tree = pygame.image.load(resource_path('resources/art/sprite_pine_tree.png')).convert_alpha()
hearth_stone = pygame.image.load(resource_path('resources/art/sprite_hearth_stone.png')).convert_alpha()
rohir_gate = pygame.image.load(resource_path('resources/art/overlay_rohir_gate.png')).convert_alpha()
lets_go_button = pygame.image.load(resource_path('resources/art/button_lets_go.png')).convert_alpha()
learn_button = pygame.image.load(resource_path('resources/art/overlay_learn.png')).convert_alpha()
skill_learn_button = pygame.image.load(resource_path('resources/art/overlay_skill_learn.png')).convert_alpha()
nascent_gate_popup = pygame.image.load(resource_path('resources/art/popup_nascent_gate.png')).convert_alpha()
level_up = pygame.image.load(resource_path('resources/art/popup_level_up.png')).convert_alpha()
close_button = pygame.image.load(resource_path('resources/art/button_close.png')).convert_alpha()
knowledge_window = pygame.image.load(resource_path('resources/art/overlay_knowledge.png')).convert_alpha()
skill_bar = pygame.image.load(resource_path('resources/art/overlay_skill_bar.png')).convert_alpha()
start_button = pygame.image.load(resource_path('resources/art/button_start.png')).convert_alpha()
npc_name_plate = pygame.image.load(resource_path('resources/art/overlay_npc_name_plate.png')).convert_alpha()
char_select_overlay = pygame.image.load(resource_path('resources/art/overlay_character_select.png')).convert_alpha()
role_selection_overlay = pygame.image.load(resource_path('resources/art/overlay_role_select.png')).convert_alpha()
location_overlay = pygame.image.load(resource_path('resources/art/overlay_location.png')).convert_alpha()
popup_interaction = pygame.image.load(resource_path('resources/art/popup_interaction.png')).convert_alpha()
popup_loot = pygame.image.load(resource_path('resources/art/popup_loot.png')).convert_alpha()
stardust_entrance = pygame.image.load(resource_path('resources/art/overlay_stardust_entrance.png')).convert_alpha()
upgrade_overlay = pygame.image.load(resource_path('resources/art/overlay_upgrade_select.png')).convert_alpha()

color_keys = [bar_backdrop, enemy_status, enemy_bar_backdrop, buy_inventory, message_box, pine_tree, hearth_stone,
              rohir_gate, lets_go_button, learn_button, skill_learn_button, nascent_gate_popup, level_up,
              close_button, knowledge_window, skill_bar, start_button, npc_name_plate, char_select_overlay,
              role_selection_overlay, location_overlay, popup_interaction, popup_loot, stardust_entrance,
              upgrade_overlay]

for image in color_keys:
    image.set_colorkey((255, 255, 255))

# sprite sheets --------------------------------------------------------------------------------------------------------
# create character screen character race selections --------------------------------------------------------------------
character_selections_url = resource_path('resources/art/overlay_character_selections.png')
character_selections_sheet = sprite_sheet((250, 350), character_selections_url)
amuna_character_img = character_selections_sheet[0]
nuldar_character_img = character_selections_sheet[1]
sorae_character_img = character_selections_sheet[2]
# race selection lore overlays -----------------------------------------------------------------------------------------
race_lore_url = resource_path('resources/art/overlays_race_select.png')
race_lore_sheet = sprite_sheet((278, 372), race_lore_url)
amuna_overlay_img = race_lore_sheet[0]
nuldar_overlay_img = race_lore_sheet[1]
sorae_overlay_img = race_lore_sheet[2]
# character name input box ---------------------------------------------------------------------------------------------
name_input_url = resource_path('resources/art/overlay_name_input.png')
name_input_sheet = sprite_sheet((300, 50), name_input_url)
name_input_img = name_input_sheet[0]
name_input_empty_img = name_input_sheet[1]
# player no role amuna race --------------------------------------------------------------------------------------------
player_no_role_amuna_down_url = resource_path('resources/art/player_no_role_amuna_down.png')
player_no_role_amuna_down_sheet = sprite_sheet((50, 75), player_no_role_amuna_down_url)
player_no_role_amuna_down_1 = player_no_role_amuna_down_sheet[0]
player_no_role_amuna_down_2 = player_no_role_amuna_down_sheet[1]
player_no_role_amuna_down_3 = player_no_role_amuna_down_sheet[2]
player_no_role_amuna_down_4 = player_no_role_amuna_down_sheet[3]
player_no_role_amuna_up_url = resource_path('resources/art/player_no_role_amuna_up.png')
player_no_role_amuna_up_sheet = sprite_sheet((50, 75), player_no_role_amuna_up_url)
player_no_role_amuna_up_1 = player_no_role_amuna_up_sheet[0]
player_no_role_amuna_up_2 = player_no_role_amuna_up_sheet[1]
player_no_role_amuna_up_3 = player_no_role_amuna_up_sheet[2]
player_no_role_amuna_up_4 = player_no_role_amuna_up_sheet[3]
player_no_role_amuna_left_url = resource_path('resources/art/player_no_role_amuna_left.png')
player_no_role_amuna_left_sheet = sprite_sheet((50, 75), player_no_role_amuna_left_url)
player_no_role_amuna_left_1 = player_no_role_amuna_left_sheet[0]
player_no_role_amuna_left_2 = player_no_role_amuna_left_sheet[1]
player_no_role_amuna_left_3 = player_no_role_amuna_left_sheet[2]
player_no_role_amuna_left_4 = player_no_role_amuna_left_sheet[3]
player_no_role_amuna_right_url = resource_path('resources/art/player_no_role_amuna_right.png')
player_no_role_amuna_right_sheet = sprite_sheet((50, 75), player_no_role_amuna_right_url)
player_no_role_amuna_right_1 = player_no_role_amuna_right_sheet[0]
player_no_role_amuna_right_2 = player_no_role_amuna_right_sheet[1]
player_no_role_amuna_right_3 = player_no_role_amuna_right_sheet[2]
player_no_role_amuna_right_4 = player_no_role_amuna_right_sheet[3]
# player no role sorae race --------------------------------------------------------------------------------------------
player_no_role_sorae_down_url = resource_path('resources/art/player_no_role_sorae_down.png')
player_no_role_sorae_down_sheet = sprite_sheet((50, 75), player_no_role_sorae_down_url)
player_no_role_sorae_down_1 = player_no_role_sorae_down_sheet[0]
player_no_role_sorae_down_2 = player_no_role_sorae_down_sheet[1]
player_no_role_sorae_down_3 = player_no_role_sorae_down_sheet[2]
player_no_role_sorae_down_4 = player_no_role_sorae_down_sheet[3]
player_no_role_sorae_up_url = resource_path('resources/art/player_no_role_sorae_up.png')
player_no_role_sorae_up_sheet = sprite_sheet((50, 75), player_no_role_sorae_up_url)
player_no_role_sorae_up_1 = player_no_role_sorae_up_sheet[0]
player_no_role_sorae_up_2 = player_no_role_sorae_up_sheet[1]
player_no_role_sorae_up_3 = player_no_role_sorae_up_sheet[2]
player_no_role_sorae_up_4 = player_no_role_sorae_up_sheet[3]
player_no_role_sorae_left_url = resource_path('resources/art/player_no_role_sorae_left.png')
player_no_role_sorae_left_sheet = sprite_sheet((50, 75), player_no_role_sorae_left_url)
player_no_role_sorae_left_1 = player_no_role_sorae_left_sheet[0]
player_no_role_sorae_left_2 = player_no_role_sorae_left_sheet[1]
player_no_role_sorae_left_3 = player_no_role_sorae_left_sheet[2]
player_no_role_sorae_left_4 = player_no_role_sorae_left_sheet[3]
player_no_role_sorae_right_url = resource_path('resources/art/player_no_role_sorae_right.png')
player_no_role_sorae_right_sheet = sprite_sheet((50, 75), player_no_role_sorae_right_url)
player_no_role_sorae_right_1 = player_no_role_sorae_right_sheet[0]
player_no_role_sorae_right_2 = player_no_role_sorae_right_sheet[1]
player_no_role_sorae_right_3 = player_no_role_sorae_right_sheet[2]
player_no_role_sorae_right_4 = player_no_role_sorae_right_sheet[3]
# player no role nuldar race -------------------------------------------------------------------------------------------
player_no_role_nuldar_down_url = resource_path('resources/art/player_no_role_nuldar_down.png')
player_no_role_nuldar_down_sheet = sprite_sheet((50, 75), player_no_role_nuldar_down_url)
player_no_role_nuldar_down_1 = player_no_role_nuldar_down_sheet[0]
player_no_role_nuldar_down_2 = player_no_role_nuldar_down_sheet[1]
player_no_role_nuldar_down_3 = player_no_role_nuldar_down_sheet[2]
player_no_role_nuldar_down_4 = player_no_role_nuldar_down_sheet[3]
player_no_role_nuldar_up_url = resource_path('resources/art/player_no_role_nuldar_up.png')
player_no_role_nuldar_up_sheet = sprite_sheet((50, 75), player_no_role_nuldar_up_url)
player_no_role_nuldar_up_1 = player_no_role_nuldar_up_sheet[0]
player_no_role_nuldar_up_2 = player_no_role_nuldar_up_sheet[1]
player_no_role_nuldar_up_3 = player_no_role_nuldar_up_sheet[2]
player_no_role_nuldar_up_4 = player_no_role_nuldar_up_sheet[3]
player_no_role_nuldar_left_url = resource_path('resources/art/player_no_role_nuldar_left.png')
player_no_role_nuldar_left_sheet = sprite_sheet((50, 75), player_no_role_nuldar_left_url)
player_no_role_nuldar_left_1 = player_no_role_nuldar_left_sheet[0]
player_no_role_nuldar_left_2 = player_no_role_nuldar_left_sheet[1]
player_no_role_nuldar_left_3 = player_no_role_nuldar_left_sheet[2]
player_no_role_nuldar_left_4 = player_no_role_nuldar_left_sheet[3]
player_no_role_nuldar_right_url = resource_path('resources/art/player_no_role_nuldar_right.png')
player_no_role_nuldar_right_sheet = sprite_sheet((50, 75), player_no_role_nuldar_right_url)
player_no_role_nuldar_right_1 = player_no_role_nuldar_right_sheet[0]
player_no_role_nuldar_right_2 = player_no_role_nuldar_right_sheet[1]
player_no_role_nuldar_right_3 = player_no_role_nuldar_right_sheet[2]
player_no_role_nuldar_right_4 = player_no_role_nuldar_right_sheet[3]
# player mage amuna race -----------------------------------------------------------------------------------------------
player_mage_amuna_down_url = resource_path('resources/art/player_mage_amuna_down.png')
player_mage_amuna_down_sheet = sprite_sheet((50, 75), player_mage_amuna_down_url)
player_mage_amuna_down_1 = player_mage_amuna_down_sheet[0]
player_mage_amuna_down_2 = player_mage_amuna_down_sheet[1]
player_mage_amuna_down_3 = player_mage_amuna_down_sheet[2]
player_mage_amuna_down_4 = player_mage_amuna_down_sheet[3]
player_mage_amuna_up_url = resource_path('resources/art/player_mage_amuna_up.png')
player_mage_amuna_up_sheet = sprite_sheet((50, 75), player_mage_amuna_up_url)
player_mage_amuna_up_1 = player_mage_amuna_up_sheet[0]
player_mage_amuna_up_2 = player_mage_amuna_up_sheet[1]
player_mage_amuna_up_3 = player_mage_amuna_up_sheet[2]
player_mage_amuna_up_4 = player_mage_amuna_up_sheet[3]
player_mage_amuna_left_url = resource_path('resources/art/player_mage_amuna_left.png')
player_mage_amuna_left_sheet = sprite_sheet((50, 75), player_mage_amuna_left_url)
player_mage_amuna_left_1 = player_mage_amuna_left_sheet[0]
player_mage_amuna_left_2 = player_mage_amuna_left_sheet[1]
player_mage_amuna_left_3 = player_mage_amuna_left_sheet[2]
player_mage_amuna_left_4 = player_mage_amuna_left_sheet[3]
player_mage_amuna_right_url = resource_path('resources/art/player_mage_amuna_right.png')
player_mage_amuna_right_sheet = sprite_sheet((50, 75), player_mage_amuna_right_url)
player_mage_amuna_right_1 = player_mage_amuna_right_sheet[0]
player_mage_amuna_right_2 = player_mage_amuna_right_sheet[1]
player_mage_amuna_right_3 = player_mage_amuna_right_sheet[2]
player_mage_amuna_right_4 = player_mage_amuna_right_sheet[3]
# player mage nuldar race ----------------------------------------------------------------------------------------------
player_mage_nuldar_down_url = resource_path('resources/art/player_mage_nuldar_down.png')
player_mage_nuldar_down_sheet = sprite_sheet((50, 75), player_mage_nuldar_down_url)
player_mage_nuldar_down_1 = player_mage_nuldar_down_sheet[0]
player_mage_nuldar_down_2 = player_mage_nuldar_down_sheet[1]
player_mage_nuldar_down_3 = player_mage_nuldar_down_sheet[2]
player_mage_nuldar_down_4 = player_mage_nuldar_down_sheet[3]
player_mage_nuldar_up_url = resource_path('resources/art/player_mage_nuldar_up.png')
player_mage_nuldar_up_sheet = sprite_sheet((50, 75), player_mage_nuldar_up_url)
player_mage_nuldar_up_1 = player_mage_nuldar_up_sheet[0]
player_mage_nuldar_up_2 = player_mage_nuldar_up_sheet[1]
player_mage_nuldar_up_3 = player_mage_nuldar_up_sheet[2]
player_mage_nuldar_up_4 = player_mage_nuldar_up_sheet[3]
player_mage_nuldar_left_url = resource_path('resources/art/player_mage_nuldar_left.png')
player_mage_nuldar_left_sheet = sprite_sheet((50, 75), player_mage_nuldar_left_url)
player_mage_nuldar_left_1 = player_mage_nuldar_left_sheet[0]
player_mage_nuldar_left_2 = player_mage_nuldar_left_sheet[1]
player_mage_nuldar_left_3 = player_mage_nuldar_left_sheet[2]
player_mage_nuldar_left_4 = player_mage_nuldar_left_sheet[3]
player_mage_nuldar_right_url = resource_path('resources/art/player_mage_nuldar_right.png')
player_mage_nuldar_right_sheet = sprite_sheet((50, 75), player_mage_nuldar_right_url)
player_mage_nuldar_right_1 = player_mage_nuldar_right_sheet[0]
player_mage_nuldar_right_2 = player_mage_nuldar_right_sheet[1]
player_mage_nuldar_right_3 = player_mage_nuldar_right_sheet[2]
player_mage_nuldar_right_4 = player_mage_nuldar_right_sheet[3]
# player mage sorae race -----------------------------------------------------------------------------------------------
player_mage_sorae_down_url = resource_path('resources/art/player_mage_sorae_down.png')
player_mage_sorae_down_sheet = sprite_sheet((50, 75), player_mage_sorae_down_url)
player_mage_sorae_down_1 = player_mage_sorae_down_sheet[0]
player_mage_sorae_down_2 = player_mage_sorae_down_sheet[1]
player_mage_sorae_down_3 = player_mage_sorae_down_sheet[2]
player_mage_sorae_down_4 = player_mage_sorae_down_sheet[3]
player_mage_sorae_up_url = resource_path('resources/art/player_mage_sorae_up.png')
player_mage_sorae_up_sheet = sprite_sheet((50, 75), player_mage_sorae_up_url)
player_mage_sorae_up_1 = player_mage_sorae_up_sheet[0]
player_mage_sorae_up_2 = player_mage_sorae_up_sheet[1]
player_mage_sorae_up_3 = player_mage_sorae_up_sheet[2]
player_mage_sorae_up_4 = player_mage_sorae_up_sheet[3]
player_mage_sorae_left_url = resource_path('resources/art/player_mage_sorae_left.png')
player_mage_sorae_left_sheet = sprite_sheet((50, 75), player_mage_sorae_left_url)
player_mage_sorae_left_1 = player_mage_sorae_left_sheet[0]
player_mage_sorae_left_2 = player_mage_sorae_left_sheet[1]
player_mage_sorae_left_3 = player_mage_sorae_left_sheet[2]
player_mage_sorae_left_4 = player_mage_sorae_left_sheet[3]
player_mage_sorae_right_url = resource_path('resources/art/player_mage_sorae_right.png')
player_mage_sorae_right_sheet = sprite_sheet((50, 75), player_mage_sorae_right_url)
player_mage_sorae_right_1 = player_mage_sorae_right_sheet[0]
player_mage_sorae_right_2 = player_mage_sorae_right_sheet[1]
player_mage_sorae_right_3 = player_mage_sorae_right_sheet[2]
player_mage_sorae_right_4 = player_mage_sorae_right_sheet[3]
# player fighter amuna race --------------------------------------------------------------------------------------------
player_fighter_amuna_down_url = resource_path('resources/art/player_fighter_amuna_down.png')
player_fighter_amuna_down_sheet = sprite_sheet((50, 75), player_fighter_amuna_down_url)
player_fighter_amuna_down_1 = player_fighter_amuna_down_sheet[0]
player_fighter_amuna_down_2 = player_fighter_amuna_down_sheet[1]
player_fighter_amuna_down_3 = player_fighter_amuna_down_sheet[2]
player_fighter_amuna_down_4 = player_fighter_amuna_down_sheet[3]
player_fighter_amuna_up_url = resource_path('resources/art/player_fighter_amuna_up.png')
player_fighter_amuna_up_sheet = sprite_sheet((50, 75), player_fighter_amuna_up_url)
player_fighter_amuna_up_1 = player_fighter_amuna_up_sheet[0]
player_fighter_amuna_up_2 = player_fighter_amuna_up_sheet[1]
player_fighter_amuna_up_3 = player_fighter_amuna_up_sheet[2]
player_fighter_amuna_up_4 = player_fighter_amuna_up_sheet[3]
player_fighter_amuna_left_url = resource_path('resources/art/player_fighter_amuna_left.png')
player_fighter_amuna_left_sheet = sprite_sheet((50, 75), player_fighter_amuna_left_url)
player_fighter_amuna_left_1 = player_fighter_amuna_left_sheet[0]
player_fighter_amuna_left_2 = player_fighter_amuna_left_sheet[1]
player_fighter_amuna_left_3 = player_fighter_amuna_left_sheet[2]
player_fighter_amuna_left_4 = player_fighter_amuna_left_sheet[3]
player_fighter_amuna_right_url = resource_path('resources/art/player_fighter_amuna_right.png')
player_fighter_amuna_right_sheet = sprite_sheet((50, 75), player_fighter_amuna_right_url)
player_fighter_amuna_right_1 = player_fighter_amuna_right_sheet[0]
player_fighter_amuna_right_2 = player_fighter_amuna_right_sheet[1]
player_fighter_amuna_right_3 = player_fighter_amuna_right_sheet[2]
player_fighter_amuna_right_4 = player_fighter_amuna_right_sheet[3]
# player fighter nuldar race -------------------------------------------------------------------------------------------
player_fighter_nuldar_down_url = resource_path('resources/art/player_fighter_nuldar_down.png')
player_fighter_nuldar_down_sheet = sprite_sheet((50, 75), player_fighter_nuldar_down_url)
player_fighter_nuldar_down_1 = player_fighter_nuldar_down_sheet[0]
player_fighter_nuldar_down_2 = player_fighter_nuldar_down_sheet[1]
player_fighter_nuldar_down_3 = player_fighter_nuldar_down_sheet[2]
player_fighter_nuldar_down_4 = player_fighter_nuldar_down_sheet[3]
player_fighter_nuldar_up_url = resource_path('resources/art/player_fighter_nuldar_up.png')
player_fighter_nuldar_up_sheet = sprite_sheet((50, 75), player_fighter_nuldar_up_url)
player_fighter_nuldar_up_1 = player_fighter_nuldar_up_sheet[0]
player_fighter_nuldar_up_2 = player_fighter_nuldar_up_sheet[1]
player_fighter_nuldar_up_3 = player_fighter_nuldar_up_sheet[2]
player_fighter_nuldar_up_4 = player_fighter_nuldar_up_sheet[3]
player_fighter_nuldar_left_url = resource_path('resources/art/player_fighter_nuldar_left.png')
player_fighter_nuldar_left_sheet = sprite_sheet((50, 75), player_fighter_nuldar_left_url)
player_fighter_nuldar_left_1 = player_fighter_nuldar_left_sheet[0]
player_fighter_nuldar_left_2 = player_fighter_nuldar_left_sheet[1]
player_fighter_nuldar_left_3 = player_fighter_nuldar_left_sheet[2]
player_fighter_nuldar_left_4 = player_fighter_nuldar_left_sheet[3]
player_fighter_nuldar_right_url = resource_path('resources/art/player_fighter_nuldar_right.png')
player_fighter_nuldar_right_sheet = sprite_sheet((50, 75), player_fighter_nuldar_right_url)
player_fighter_nuldar_right_1 = player_fighter_nuldar_right_sheet[0]
player_fighter_nuldar_right_2 = player_fighter_nuldar_right_sheet[1]
player_fighter_nuldar_right_3 = player_fighter_nuldar_right_sheet[2]
player_fighter_nuldar_right_4 = player_fighter_nuldar_right_sheet[3]
# player fighter sorae race --------------------------------------------------------------------------------------------
player_fighter_sorae_down_url = resource_path('resources/art/player_fighter_sorae_down.png')
player_fighter_sorae_down_sheet = sprite_sheet((50, 75), player_fighter_sorae_down_url)
player_fighter_sorae_down_1 = player_fighter_sorae_down_sheet[0]
player_fighter_sorae_down_2 = player_fighter_sorae_down_sheet[1]
player_fighter_sorae_down_3 = player_fighter_sorae_down_sheet[2]
player_fighter_sorae_down_4 = player_fighter_sorae_down_sheet[3]
player_fighter_sorae_up_url = resource_path('resources/art/player_fighter_sorae_up.png')
player_fighter_sorae_up_sheet = sprite_sheet((50, 75), player_fighter_sorae_up_url)
player_fighter_sorae_up_1 = player_fighter_sorae_up_sheet[0]
player_fighter_sorae_up_2 = player_fighter_sorae_up_sheet[1]
player_fighter_sorae_up_3 = player_fighter_sorae_up_sheet[2]
player_fighter_sorae_up_4 = player_fighter_sorae_up_sheet[3]
player_fighter_sorae_left_url = resource_path('resources/art/player_fighter_sorae_left.png')
player_fighter_sorae_left_sheet = sprite_sheet((50, 75), player_fighter_sorae_left_url)
player_fighter_sorae_left_1 = player_fighter_sorae_left_sheet[0]
player_fighter_sorae_left_2 = player_fighter_sorae_left_sheet[1]
player_fighter_sorae_left_3 = player_fighter_sorae_left_sheet[2]
player_fighter_sorae_left_4 = player_fighter_sorae_left_sheet[3]
player_fighter_sorae_right_url = resource_path('resources/art/player_fighter_sorae_right.png')
player_fighter_sorae_right_sheet = sprite_sheet((50, 75), player_fighter_sorae_right_url)
player_fighter_sorae_right_1 = player_fighter_sorae_right_sheet[0]
player_fighter_sorae_right_2 = player_fighter_sorae_right_sheet[1]
player_fighter_sorae_right_3 = player_fighter_sorae_right_sheet[2]
player_fighter_sorae_right_4 = player_fighter_sorae_right_sheet[3]
# player scout amuna race ----------------------------------------------------------------------------------------------
player_scout_amuna_down_url = resource_path('resources/art/player_scout_amuna_down.png')
player_scout_amuna_down_sheet = sprite_sheet((50, 75), player_scout_amuna_down_url)
player_scout_amuna_down_1 = player_scout_amuna_down_sheet[0]
player_scout_amuna_down_2 = player_scout_amuna_down_sheet[1]
player_scout_amuna_down_3 = player_scout_amuna_down_sheet[2]
player_scout_amuna_down_4 = player_scout_amuna_down_sheet[3]
player_scout_amuna_up_url = resource_path('resources/art/player_scout_amuna_up.png')
player_scout_amuna_up_sheet = sprite_sheet((50, 75), player_scout_amuna_up_url)
player_scout_amuna_up_1 = player_scout_amuna_up_sheet[0]
player_scout_amuna_up_2 = player_scout_amuna_up_sheet[1]
player_scout_amuna_up_3 = player_scout_amuna_up_sheet[2]
player_scout_amuna_up_4 = player_scout_amuna_up_sheet[3]
player_scout_amuna_left_url = resource_path('resources/art/player_scout_amuna_left.png')
player_scout_amuna_left_sheet = sprite_sheet((50, 75), player_scout_amuna_left_url)
player_scout_amuna_left_1 = player_scout_amuna_left_sheet[0]
player_scout_amuna_left_2 = player_scout_amuna_left_sheet[1]
player_scout_amuna_left_3 = player_scout_amuna_left_sheet[2]
player_scout_amuna_left_4 = player_scout_amuna_left_sheet[3]
player_scout_amuna_right_url = resource_path('resources/art/player_scout_amuna_right.png')
player_scout_amuna_right_sheet = sprite_sheet((50, 75), player_scout_amuna_right_url)
player_scout_amuna_right_1 = player_scout_amuna_right_sheet[0]
player_scout_amuna_right_2 = player_scout_amuna_right_sheet[1]
player_scout_amuna_right_3 = player_scout_amuna_right_sheet[2]
player_scout_amuna_right_4 = player_scout_amuna_right_sheet[3]
# player scout nuldar race ---------------------------------------------------------------------------------------------
player_scout_nuldar_down_url = resource_path('resources/art/player_scout_nuldar_down.png')
player_scout_nuldar_down_sheet = sprite_sheet((50, 75), player_scout_nuldar_down_url)
player_scout_nuldar_down_1 = player_scout_nuldar_down_sheet[0]
player_scout_nuldar_down_2 = player_scout_nuldar_down_sheet[1]
player_scout_nuldar_down_3 = player_scout_nuldar_down_sheet[2]
player_scout_nuldar_down_4 = player_scout_nuldar_down_sheet[3]
player_scout_nuldar_up_url = resource_path('resources/art/player_scout_nuldar_up.png')
player_scout_nuldar_up_sheet = sprite_sheet((50, 75), player_scout_nuldar_up_url)
player_scout_nuldar_up_1 = player_scout_nuldar_up_sheet[0]
player_scout_nuldar_up_2 = player_scout_nuldar_up_sheet[1]
player_scout_nuldar_up_3 = player_scout_nuldar_up_sheet[2]
player_scout_nuldar_up_4 = player_scout_nuldar_up_sheet[3]
player_scout_nuldar_left_url = resource_path('resources/art/player_scout_nuldar_left.png')
player_scout_nuldar_left_sheet = sprite_sheet((50, 75), player_scout_nuldar_left_url)
player_scout_nuldar_left_1 = player_scout_nuldar_left_sheet[0]
player_scout_nuldar_left_2 = player_scout_nuldar_left_sheet[1]
player_scout_nuldar_left_3 = player_scout_nuldar_left_sheet[2]
player_scout_nuldar_left_4 = player_scout_nuldar_left_sheet[3]
player_scout_nuldar_right_url = resource_path('resources/art/player_scout_nuldar_right.png')
player_scout_nuldar_right_sheet = sprite_sheet((50, 75), player_scout_nuldar_right_url)
player_scout_nuldar_right_1 = player_scout_nuldar_right_sheet[0]
player_scout_nuldar_right_2 = player_scout_nuldar_right_sheet[1]
player_scout_nuldar_right_3 = player_scout_nuldar_right_sheet[2]
player_scout_nuldar_right_4 = player_scout_nuldar_right_sheet[3]
# player scout sorae race ----------------------------------------------------------------------------------------------
player_scout_sorae_down_url = resource_path('resources/art/player_scout_sorae_down.png')
player_scout_sorae_down_sheet = sprite_sheet((50, 75), player_scout_sorae_down_url)
player_scout_sorae_down_1 = player_scout_sorae_down_sheet[0]
player_scout_sorae_down_2 = player_scout_sorae_down_sheet[1]
player_scout_sorae_down_3 = player_scout_sorae_down_sheet[2]
player_scout_sorae_down_4 = player_scout_sorae_down_sheet[3]
player_scout_sorae_up_url = resource_path('resources/art/player_scout_sorae_up.png')
player_scout_sorae_up_sheet = sprite_sheet((50, 75), player_scout_sorae_up_url)
player_scout_sorae_up_1 = player_scout_sorae_up_sheet[0]
player_scout_sorae_up_2 = player_scout_sorae_up_sheet[1]
player_scout_sorae_up_3 = player_scout_sorae_up_sheet[2]
player_scout_sorae_up_4 = player_scout_sorae_up_sheet[3]
player_scout_sorae_left_url = resource_path('resources/art/player_scout_sorae_left.png')
player_scout_sorae_left_sheet = sprite_sheet((50, 75), player_scout_sorae_left_url)
player_scout_sorae_left_1 = player_scout_sorae_left_sheet[0]
player_scout_sorae_left_2 = player_scout_sorae_left_sheet[1]
player_scout_sorae_left_3 = player_scout_sorae_left_sheet[2]
player_scout_sorae_left_4 = player_scout_sorae_left_sheet[3]
player_scout_sorae_right_url = resource_path('resources/art/player_scout_sorae_right.png')
player_scout_sorae_right_sheet = sprite_sheet((50, 75), player_scout_sorae_right_url)
player_scout_sorae_right_1 = player_scout_sorae_right_sheet[0]
player_scout_sorae_right_2 = player_scout_sorae_right_sheet[1]
player_scout_sorae_right_3 = player_scout_sorae_right_sheet[2]
player_scout_sorae_right_4 = player_scout_sorae_right_sheet[3]
# player battle amuna race ---------------------------------------------------------------------------------------------
player_battle_amuna_url = resource_path('resources/art/player_battle_sprites_amuna.png')
player_battle_amuna_sheet = sprite_sheet((750, 624), player_battle_amuna_url)
player_no_role_amuna_battle = player_battle_amuna_sheet[0]
player_no_role_amuna_attack = player_battle_amuna_sheet[1]
player_mage_amuna_battle = player_battle_amuna_sheet[2]
player_mage_amuna_attack = player_battle_amuna_sheet[3]
player_fighter_amuna_battle = player_battle_amuna_sheet[4]
player_fighter_amuna_attack = player_battle_amuna_sheet[5]
player_scout_amuna_battle = player_battle_amuna_sheet[6]
player_scout_amuna_attack = player_battle_amuna_sheet[7]
# player skills amuna race ---------------------------------------------------------------------------------------------
player_skills_amuna_url = resource_path('resources/art/player_battle_sprites_skills_amuna.png')
player_skills_amuna_sheet = sprite_sheet((750, 624), player_skills_amuna_url)
player_mage_barrier_amuna_battle = player_skills_amuna_sheet[0]
player_mage_barrier_amuna_attack = player_skills_amuna_sheet[1]
player_scout_sense_amuna_battle = player_skills_amuna_sheet[2]
player_scout_sense_amuna_attack = player_skills_amuna_sheet[3]
player_fighter_amuna_strike = player_skills_amuna_sheet[4]
# damage overlays ------------------------------------------------------------------------------------------------------
damage_overlays_url = resource_path('resources/art/overlays_damage.png')
damage_overlays_sheet = sprite_sheet((150, 150), damage_overlays_url)
dealt_damage_img = damage_overlays_sheet[0]
received_damage_img = damage_overlays_sheet[1]
# player battle sorae race ---------------------------------------------------------------------------------------------
player_battle_sorae_url = resource_path('resources/art/player_battle_sprites_sorae.png')
player_battle_sorae_sheet = sprite_sheet((750, 624), player_battle_sorae_url)
player_no_role_sorae_battle = player_battle_sorae_sheet[0]
player_no_role_sorae_attack = player_battle_sorae_sheet[1]
player_mage_sorae_battle = player_battle_sorae_sheet[2]
player_mage_sorae_attack = player_battle_sorae_sheet[3]
player_fighter_sorae_battle = player_battle_sorae_sheet[4]
player_fighter_sorae_attack = player_battle_sorae_sheet[5]
player_scout_sorae_battle = player_battle_sorae_sheet[6]
player_scout_sorae_attack = player_battle_sorae_sheet[7]
# player skills sorae race ---------------------------------------------------------------------------------------------
player_skills_sorae_url = resource_path('resources/art/player_battle_sprites_skills_sorae.png')
player_skills_sorae_sheet = sprite_sheet((750, 624), player_skills_sorae_url)
player_mage_barrier_sorae_battle = player_skills_sorae_sheet[0]
player_mage_barrier_sorae_attack = player_skills_sorae_sheet[1]
player_scout_sense_sorae_battle = player_skills_sorae_sheet[2]
player_scout_sense_sorae_attack = player_skills_sorae_sheet[3]
player_fighter_sorae_strike = player_skills_sorae_sheet[4]
# player battle nuldar race --------------------------------------------------------------------------------------------
player_battle_nuldar_url = resource_path('resources/art/player_battle_sprites_nuldar.png')
player_battle_nuldar_sheet = sprite_sheet((750, 624), player_battle_nuldar_url)
player_no_role_nuldar_battle = player_battle_nuldar_sheet[0]
player_no_role_nuldar_attack = player_battle_nuldar_sheet[1]
player_mage_nuldar_battle = player_battle_nuldar_sheet[2]
player_mage_nuldar_attack = player_battle_nuldar_sheet[3]
player_fighter_nuldar_battle = player_battle_nuldar_sheet[4]
player_fighter_nuldar_attack = player_battle_nuldar_sheet[5]
player_scout_nuldar_battle = player_battle_nuldar_sheet[6]
player_scout_nuldar_attack = player_battle_nuldar_sheet[7]
# player skills sorae race ---------------------------------------------------------------------------------------------
player_skills_nuldar_url = resource_path('resources/art/player_battle_sprites_skills_nuldar.png')
player_skills_nuldar_sheet = sprite_sheet((750, 624), player_skills_nuldar_url)
player_mage_barrier_nuldar_battle = player_skills_nuldar_sheet[0]
player_mage_barrier_nuldar_attack = player_skills_nuldar_sheet[1]
player_scout_sense_nuldar_battle = player_skills_nuldar_sheet[2]
player_scout_sense_nuldar_attack = player_skills_nuldar_sheet[3]
player_fighter_nuldar_strike = player_skills_nuldar_sheet[4]
# garan npc ------------------------------------------------------------------------------------------------------------
garan_url = resource_path('resources/art/sprites_garans.png')
garan_sheet = sprite_sheet((40, 62), garan_url)
garan_down = garan_sheet[0]
garan_up = garan_sheet[1]
garan_left = garan_sheet[2]
garan_right = garan_sheet[3]
# maurelle npc ---------------------------------------------------------------------------------------------------------
maurelle_url = resource_path('resources/art/sprites_maurelles.png')
maurelle_sheet = sprite_sheet((40, 62), maurelle_url)
maurelle_down = maurelle_sheet[0]
maurelle_up = maurelle_sheet[1]
maurelle_left = maurelle_sheet[2]
maurelle_right = maurelle_sheet[3]
# celeste npc ----------------------------------------------------------------------------------------------------------
celeste_url = resource_path('resources/art/sprites_celestes.png')
celeste_sheet = sprite_sheet((45, 62), celeste_url)
celeste_down = celeste_sheet[0]
celeste_up = celeste_sheet[1]
celeste_left = celeste_sheet[2]
celeste_right = celeste_sheet[3]
# nede sprite ----------------------------------------------------------------------------------------------------------
nede_url = resource_path('resources/art/sprites_nede.png')
nede_sheet = sprite_sheet((60, 60), nede_url)
nede_left = nede_sheet[0]
nede_right = nede_sheet[1]
nede_high_left = nede_sheet[2]
nede_high_right = nede_sheet[3]
# guard npc ------------------------------------------------------------------------------------------------------------
guard_url = resource_path('resources/art/sprites_guards.png')
guard_sheet = sprite_sheet((50, 62), guard_url)
guard_down = guard_sheet[0]
guard_up = guard_sheet[1]
guard_left = guard_sheet[2]
guard_right = guard_sheet[3]
# torune npc -----------------------------------------------------------------------------------------------------------
torune_url = resource_path('resources/art/sprites_torune.png')
torune_sheet = sprite_sheet((50, 62), torune_url)
torune_down = torune_sheet[0]
torune_up = torune_sheet[1]
torune_left = torune_sheet[2]
torune_right = torune_sheet[3]
# npc interactions -----------------------------------------------------------------------------------------------------
npc_interactions_url = resource_path('resources/art/sprites_npc_interactions.png')
npc_interactions_sheet = sprite_sheet((220, 300), npc_interactions_url)
garan_interaction = npc_interactions_sheet[0]
maurelle_interaction = npc_interactions_sheet[1]
celeste_interaction = npc_interactions_sheet[2]
torune_interaction = npc_interactions_sheet[3]
# enemies --------------------------------------------------------------------------------------------------------------
enemies_url = resource_path('resources/art/sprites_enemies.png')
enemies_sheet = sprite_sheet((50, 50), enemies_url)
snake = enemies_sheet[0]
ghoul = enemies_sheet[1]
# enemies highlighted --------------------------------------------------------------------------------------------------
enemies_high_url = resource_path('resources/art/sprites_enemies_highlighted.png')
enemies_high_sheet = sprite_sheet((50, 50), enemies_high_url)
snake_high = enemies_high_sheet[0]
ghoul_high = enemies_high_sheet[1]
# enemies battle -------------------------------------------------------------------------------------------------------
enemies_battle_url = resource_path('resources/art/sprites_enemies_battle.png')
enemies_battle_sheet = sprite_sheet((300, 280), enemies_battle_url)
snake_battle = enemies_battle_sheet[0]
snake_attack = enemies_battle_sheet[1]
ghoul_battle = enemies_battle_sheet[2]
ghoul_attack = enemies_battle_sheet[3]
# amuna buildings ------------------------------------------------------------------------------------------------------
amuna_buildings_url = resource_path('resources/art/sprites_amuna_buildings.png')
amuna_buildings_sheet = sprite_sheet((100, 100), amuna_buildings_url)
amuna_academia_building = amuna_buildings_sheet[0]
amuna_inn_building = amuna_buildings_sheet[1]
amuna_shop_building = amuna_buildings_sheet[2]
# nascent gate ---------------------------------------------------------------------------------------------------------
nascent_gate_url = resource_path('resources/art/sprites_nascent_gate.png')
nascent_gate_sheet = sprite_sheet((178, 120), nascent_gate_url)
nascent_gate_closed = nascent_gate_sheet[0]
nascent_gate_open = nascent_gate_sheet[1]
# items ----------------------------------------------------------------------------------------------------------------
items_url = resource_path('resources/art/overlay_items.png')
items_sheet = sprite_sheet((50, 50), items_url)
health_pot_img = items_sheet[0]
energy_pot_img = items_sheet[1]
basic_robes_img = items_sheet[2]
basic_armor_img = items_sheet[3]
basic_tunic_img = items_sheet[4]
basic_staff_img = items_sheet[5]
basic_sword_img = items_sheet[6]
basic_bow_img = items_sheet[7]
bone_dust_img = items_sheet[8]
shiny_rock_img = items_sheet[9]
temp_img = items_sheet[10]
# items info -----------------------------------------------------------------------------------------------------------
items_info_url = resource_path('resources/art/overlay_info_items.png')
items_info_sheet = sprite_sheet((246, 240), items_info_url)
info_health_pot_img = items_info_sheet[0]
info_energy_pot_img = items_info_sheet[1]
info_basic_robes_img = items_info_sheet[2]
info_basic_armor_img = items_info_sheet[3]
info_basic_tunic_img = items_info_sheet[4]
info_basic_staff_img = items_info_sheet[5]
info_basic_sword_img = items_info_sheet[6]
info_basic_bow_img = items_info_sheet[7]
info_bone_dust_img = items_info_sheet[8]
info_shiny_rock_img = items_info_sheet[9]
# buy items info -------------------------------------------------------------------------------------------------------
buy_items_url = resource_path('resources/art/overlay_buy_items.png')
buy_items_sheet = sprite_sheet((246, 240), buy_items_url)
b_health_pot_img = buy_items_sheet[0]
b_energy_pot_img = buy_items_sheet[1]
b_basic_robes_img = buy_items_sheet[2]
b_basic_armor_img = buy_items_sheet[3]
b_basic_tunic_img = buy_items_sheet[4]
b_basic_staff_img = buy_items_sheet[5]
b_basic_sword_img = buy_items_sheet[6]
b_basic_bow_img = buy_items_sheet[7]
# sell items -----------------------------------------------------------------------------------------------------------
sell_items_url = resource_path('resources/art/overlay_sell_items.png')
sell_items_sheet = sprite_sheet((246, 240), sell_items_url)
s_health_pot_img = sell_items_sheet[0]
s_energy_pot_img = sell_items_sheet[1]
s_basic_robes_img = sell_items_sheet[2]
s_basic_armor_img = sell_items_sheet[3]
s_basic_tunic_img = sell_items_sheet[4]
s_basic_staff_img = sell_items_sheet[5]
s_basic_sword_img = sell_items_sheet[6]
s_basic_bow_img = sell_items_sheet[7]
s_bone_dust_img = sell_items_sheet[8]
s_shiny_rock_img = sell_items_sheet[9]
# player info windows --------------------------------------------------------------------------------------------------
player_info_url = resource_path('resources/art/overlay_info_sheets.png')
player_info_sheet = sprite_sheet((500, 525), player_info_url)
character_window_img = player_info_sheet[0]
journal_window_img = player_info_sheet[1]
# books ----------------------------------------------------------------------------------------------------------------
books_url = resource_path('resources/art/overlay_role_books.png')
books_sheet = sprite_sheet((700, 525), books_url)
mage_book_img = books_sheet[0]
fighter_book_img = books_sheet[1]
scout_book_img = books_sheet[2]
# start screen buttons -------------------------------------------------------------------------------------------------
start_buttons_url = resource_path('resources/art/buttons_start_screen.png')
start_buttons_sheet = sprite_sheet((385, 75), start_buttons_url)
new_game_img = start_buttons_sheet[0]
continue_img = start_buttons_sheet[1]
# race select buttons on character screen ------------------------------------------------------------------------------
race_select_buttons_url = resource_path('resources/art/buttons_race_select.png')
race_select_buttons_sheet = sprite_sheet((384, 75), race_select_buttons_url)
amuna_button_img = race_select_buttons_sheet[0]
nuldar_button_img = race_select_buttons_sheet[1]
sorae_button_img = race_select_buttons_sheet[2]
# buttons --------------------------------------------------------------------------------------------------------------
buttons_url = resource_path('resources/art/buttons_main.png')
buttons_sheet = sprite_sheet((100, 50), buttons_url)
character_button_img = buttons_sheet[0]
journal_button_img = buttons_sheet[1]
buy_button_img = buttons_sheet[2]
rest_button_img = buttons_sheet[3]
quest_button_img = buttons_sheet[4]
leave_button_img = buttons_sheet[5]
accept_button_img = buttons_sheet[6]
decline_button_img = buttons_sheet[7]
yes_button_img = buttons_sheet[8]
no_button_img = buttons_sheet[9]
use_button_img = buttons_sheet[10]
equip_button_img = buttons_sheet[11]
upgrade_button_img = buttons_sheet[12]
# attack buttons -------------------------------------------------------------------------------------------------------
attack_buttons_url = resource_path('resources/art/overlay_attacks.png')
attack_buttons_sheet = sprite_sheet((60, 60), attack_buttons_url)
mage_attack_button_img = attack_buttons_sheet[0]
fighter_attack_button_img = attack_buttons_sheet[1]
scout_attack_button_img = attack_buttons_sheet[2]
no_role_attack_button_img = attack_buttons_sheet[3]
# skill buttons --------------------------------------------------------------------------------------------------------
skill_buttons_url = resource_path('resources/art/overlay_skills.png')
skill_buttons_sheet = sprite_sheet((60, 60), skill_buttons_url)
barrier_button_img = skill_buttons_sheet[0]
strike_button_img = skill_buttons_sheet[1]
sense_button_img = skill_buttons_sheet[2]
# function buttons -----------------------------------------------------------------------------------------------------
game_play_function_buttons_url = resource_path('resources/art/buttons_game_play_function.png')
game_play_function_buttons_sheet = sprite_sheet((100, 25), game_play_function_buttons_url)
save_button_img = game_play_function_buttons_sheet[0]
hearth_button_img = game_play_function_buttons_sheet[1]
# select buttons --------------------------------------------------------------------------------------------------
selection_buttons_url = resource_path('resources/art/buttons_select_role.png')
selection_buttons_sheet = sprite_sheet((184, 42), selection_buttons_url)
mage_select_button_img = selection_buttons_sheet[0]
fighter_select_button_img = selection_buttons_sheet[1]
scout_select_button_img = selection_buttons_sheet[2]
offense_select_button_img = selection_buttons_sheet[3]
defense_select_button_img = selection_buttons_sheet[4]
# quest windows --------------------------------------------------------------------------------------------------------
quest_windows_url = resource_path('resources/art/overlay_quest_sheets.png')
quest_windows_sheet = sprite_sheet((500, 525), quest_windows_url)
garan_quest = quest_windows_sheet[0]
maurelle_quest = quest_windows_sheet[1]
torune_quest = quest_windows_sheet[2]
celeste_quest = quest_windows_sheet[3]
# quest complete popups ------------------------------------------------------------------------------------------------
quest_popups_url = resource_path('resources/art/overlay_quest_completes.png')
quest_popups_sheet = sprite_sheet((500, 250), quest_popups_url)
garan_complete = quest_popups_sheet[0]
maurelle_complete = quest_popups_sheet[1]
celeste_complete = quest_popups_sheet[2]
torune_complete = quest_popups_sheet[3]
# quest stars ----------------------------------------------------------------------------------------------------------
quest_stars_url = resource_path('resources/art/overlay_quest_stars.png')
quest_stars_sheet = sprite_sheet((50, 50), quest_stars_url)
quest_start_star = quest_stars_sheet[0]
quest_progress_star = quest_stars_sheet[1]
quest_complete_star = quest_stars_sheet[2]
# star power -----------------------------------------------------------------------------------------------------------
star_power_url = resource_path('resources/art/overlay_star_power.png')
star_power_sheet = sprite_sheet((150, 50), star_power_url)
star_00 = star_power_sheet[0]
star_01 = star_power_sheet[1]
star_02 = star_power_sheet[2]
star_03 = star_power_sheet[3]
star_04 = star_power_sheet[4]
# pop up notifications -------------------------------------------------------------------------------------------------
popups_url = resource_path('resources/art/popups_main.png')
popups_sheet = sprite_sheet((400, 200), popups_url)
gear_popup = popups_sheet[0]
health_popup = popups_sheet[1]
knowledge_popup = popups_sheet[2]
save_popup = popups_sheet[3]
save_not_found = popups_sheet[4]
# quest pine logs ------------------------------------------------------------------------------------------------------
quest_logs_url = resource_path('resources/art/sprite_logs.png')
quest_logs_sheet = sprite_sheet((40, 45), quest_logs_url)
pine_logs_img = quest_logs_sheet[0]
pine_logs_high_img = quest_logs_sheet[1]
# heath bars -----------------------------------------------------------------------------------------------------------
hp_url = resource_path('resources/art/bars_health.png')
hp_sheet = sprite_sheet((305, 19), hp_url)
hp_0 = hp_sheet[0]
hp_1 = hp_sheet[1]
hp_2 = hp_sheet[2]
hp_3 = hp_sheet[3]
hp_4 = hp_sheet[4]
hp_5 = hp_sheet[5]
hp_6 = hp_sheet[6]
hp_7 = hp_sheet[7]
hp_8 = hp_sheet[8]
hp_9 = hp_sheet[9]
hp_10 = hp_sheet[10]
hp_11 = hp_sheet[11]
hp_12 = hp_sheet[12]
hp_13 = hp_sheet[13]
hp_14 = hp_sheet[14]
hp_15 = hp_sheet[15]
hp_16 = hp_sheet[16]
hp_17 = hp_sheet[17]
hp_18 = hp_sheet[18]
hp_19 = hp_sheet[19]
hp_20 = hp_sheet[20]
hp_21 = hp_sheet[21]
hp_22 = hp_sheet[22]
hp_23 = hp_sheet[23]
hp_24 = hp_sheet[24]
hp_25 = hp_sheet[25]
hp_26 = hp_sheet[26]
hp_27 = hp_sheet[27]
hp_28 = hp_sheet[28]
hp_29 = hp_sheet[29]
hp_30 = hp_sheet[30]
hp_31 = hp_sheet[31]
hp_32 = hp_sheet[32]
hp_33 = hp_sheet[33]
hp_34 = hp_sheet[34]
hp_35 = hp_sheet[35]
hp_36 = hp_sheet[36]
hp_37 = hp_sheet[37]
hp_38 = hp_sheet[38]
hp_39 = hp_sheet[39]
hp_40 = hp_sheet[40]
hp_41 = hp_sheet[41]
hp_42 = hp_sheet[42]
hp_43 = hp_sheet[43]
hp_44 = hp_sheet[44]
hp_45 = hp_sheet[45]
hp_46 = hp_sheet[46]
hp_47 = hp_sheet[47]
hp_48 = hp_sheet[48]
hp_49 = hp_sheet[49]
hp_50 = hp_sheet[50]
hp_51 = hp_sheet[51]
hp_52 = hp_sheet[52]
hp_53 = hp_sheet[53]
hp_54 = hp_sheet[54]
hp_55 = hp_sheet[55]
hp_56 = hp_sheet[56]
hp_57 = hp_sheet[57]
hp_58 = hp_sheet[58]
hp_59 = hp_sheet[59]
hp_60 = hp_sheet[60]
hp_61 = hp_sheet[61]
hp_62 = hp_sheet[62]
hp_63 = hp_sheet[63]
hp_64 = hp_sheet[64]
hp_65 = hp_sheet[65]
hp_66 = hp_sheet[66]
hp_67 = hp_sheet[67]
hp_68 = hp_sheet[68]
hp_69 = hp_sheet[69]
hp_70 = hp_sheet[70]
hp_71 = hp_sheet[71]
hp_72 = hp_sheet[72]
hp_73 = hp_sheet[73]
hp_74 = hp_sheet[74]
hp_75 = hp_sheet[75]
hp_76 = hp_sheet[76]
hp_77 = hp_sheet[77]
hp_78 = hp_sheet[78]
hp_79 = hp_sheet[79]
hp_80 = hp_sheet[80]
hp_81 = hp_sheet[81]
hp_82 = hp_sheet[82]
hp_83 = hp_sheet[83]
hp_84 = hp_sheet[84]
hp_85 = hp_sheet[85]
hp_86 = hp_sheet[86]
hp_87 = hp_sheet[87]
hp_88 = hp_sheet[88]
hp_89 = hp_sheet[89]
hp_90 = hp_sheet[90]
hp_91 = hp_sheet[91]
hp_92 = hp_sheet[92]
hp_93 = hp_sheet[93]
hp_94 = hp_sheet[94]
hp_95 = hp_sheet[95]
hp_96 = hp_sheet[96]
hp_97 = hp_sheet[97]
hp_98 = hp_sheet[98]
hp_99 = hp_sheet[99]
hp_100 = hp_sheet[100]
# energy bars ----------------------------------------------------------------------------------------------------------
en_url = resource_path('resources/art/bars_energy.png')
en_sheet = sprite_sheet((305, 19), en_url)
en_0 = en_sheet[0]
en_1 = en_sheet[1]
en_2 = en_sheet[2]
en_3 = en_sheet[3]
en_4 = en_sheet[4]
en_5 = en_sheet[5]
en_6 = en_sheet[6]
en_7 = en_sheet[7]
en_8 = en_sheet[8]
en_9 = en_sheet[9]
en_10 = en_sheet[10]
en_11 = en_sheet[11]
en_12 = en_sheet[12]
en_13 = en_sheet[13]
en_14 = en_sheet[14]
en_15 = en_sheet[15]
en_16 = en_sheet[16]
en_17 = en_sheet[17]
en_18 = en_sheet[18]
en_19 = en_sheet[19]
en_20 = en_sheet[20]
en_21 = en_sheet[21]
en_22 = en_sheet[22]
en_23 = en_sheet[23]
en_24 = en_sheet[24]
en_25 = en_sheet[25]
en_26 = en_sheet[26]
en_27 = en_sheet[27]
en_28 = en_sheet[28]
en_29 = en_sheet[29]
en_30 = en_sheet[30]
en_31 = en_sheet[31]
en_32 = en_sheet[32]
en_33 = en_sheet[33]
en_34 = en_sheet[34]
en_35 = en_sheet[35]
en_36 = en_sheet[36]
en_37 = en_sheet[37]
en_38 = en_sheet[38]
en_39 = en_sheet[39]
en_40 = en_sheet[40]
en_41 = en_sheet[41]
en_42 = en_sheet[42]
en_43 = en_sheet[43]
en_44 = en_sheet[44]
en_45 = en_sheet[45]
en_46 = en_sheet[46]
en_47 = en_sheet[47]
en_48 = en_sheet[48]
en_49 = en_sheet[49]
en_50 = en_sheet[50]
en_51 = en_sheet[51]
en_52 = en_sheet[52]
en_53 = en_sheet[53]
en_54 = en_sheet[54]
en_55 = en_sheet[55]
en_56 = en_sheet[56]
en_57 = en_sheet[57]
en_58 = en_sheet[58]
en_59 = en_sheet[59]
en_60 = en_sheet[60]
en_61 = en_sheet[61]
en_62 = en_sheet[62]
en_63 = en_sheet[63]
en_64 = en_sheet[64]
en_65 = en_sheet[65]
en_66 = en_sheet[66]
en_67 = en_sheet[67]
en_68 = en_sheet[68]
en_69 = en_sheet[69]
en_70 = en_sheet[70]
en_71 = en_sheet[71]
en_72 = en_sheet[72]
en_73 = en_sheet[73]
en_74 = en_sheet[74]
en_75 = en_sheet[75]
en_76 = en_sheet[76]
en_77 = en_sheet[77]
en_78 = en_sheet[78]
en_79 = en_sheet[79]
en_80 = en_sheet[80]
en_81 = en_sheet[81]
en_82 = en_sheet[82]
en_83 = en_sheet[83]
en_84 = en_sheet[84]
en_85 = en_sheet[85]
en_86 = en_sheet[86]
en_87 = en_sheet[87]
en_88 = en_sheet[88]
en_89 = en_sheet[89]
en_90 = en_sheet[90]
en_91 = en_sheet[91]
en_92 = en_sheet[92]
en_93 = en_sheet[93]
en_94 = en_sheet[94]
en_95 = en_sheet[95]
en_96 = en_sheet[96]
en_97 = en_sheet[97]
en_98 = en_sheet[98]
en_99 = en_sheet[99]
en_100 = en_sheet[100]
# energy bars ----------------------------------------------------------------------------------------------------------
xp_url = resource_path('resources/art/bars_xp.png')
xp_sheet = sprite_sheet((305, 19), xp_url)
xp_0 = xp_sheet[0]
xp_1 = xp_sheet[1]
xp_2 = xp_sheet[2]
xp_3 = xp_sheet[3]
xp_4 = xp_sheet[4]
xp_5 = xp_sheet[5]
xp_6 = xp_sheet[6]
xp_7 = xp_sheet[7]
xp_8 = xp_sheet[8]
xp_9 = xp_sheet[9]
xp_10 = xp_sheet[10]
xp_11 = xp_sheet[11]
xp_12 = xp_sheet[12]
xp_13 = xp_sheet[13]
xp_14 = xp_sheet[14]
xp_15 = xp_sheet[15]
xp_16 = xp_sheet[16]
xp_17 = xp_sheet[17]
xp_18 = xp_sheet[18]
xp_19 = xp_sheet[19]
xp_20 = xp_sheet[20]
xp_21 = xp_sheet[21]
xp_22 = xp_sheet[22]
xp_23 = xp_sheet[23]
xp_24 = xp_sheet[24]
xp_25 = xp_sheet[25]
xp_26 = xp_sheet[26]
xp_27 = xp_sheet[27]
xp_28 = xp_sheet[28]
xp_29 = xp_sheet[29]
xp_30 = xp_sheet[30]
xp_31 = xp_sheet[31]
xp_32 = xp_sheet[32]
xp_33 = xp_sheet[33]
xp_34 = xp_sheet[34]
xp_35 = xp_sheet[35]
xp_36 = xp_sheet[36]
xp_37 = xp_sheet[37]
xp_38 = xp_sheet[38]
xp_39 = xp_sheet[39]
xp_40 = xp_sheet[40]
xp_41 = xp_sheet[41]
xp_42 = xp_sheet[42]
xp_43 = xp_sheet[43]
xp_44 = xp_sheet[44]
xp_45 = xp_sheet[45]
xp_46 = xp_sheet[46]
xp_47 = xp_sheet[47]
xp_48 = xp_sheet[48]
xp_49 = xp_sheet[49]
xp_50 = xp_sheet[50]
xp_51 = xp_sheet[51]
xp_52 = xp_sheet[52]
xp_53 = xp_sheet[53]
xp_54 = xp_sheet[54]
xp_55 = xp_sheet[55]
xp_56 = xp_sheet[56]
xp_57 = xp_sheet[57]
xp_58 = xp_sheet[58]
xp_59 = xp_sheet[59]
xp_60 = xp_sheet[60]
xp_61 = xp_sheet[61]
xp_62 = xp_sheet[62]
xp_63 = xp_sheet[63]
xp_64 = xp_sheet[64]
xp_65 = xp_sheet[65]
xp_66 = xp_sheet[66]
xp_67 = xp_sheet[67]
xp_68 = xp_sheet[68]
xp_69 = xp_sheet[69]
xp_70 = xp_sheet[70]
xp_71 = xp_sheet[71]
xp_72 = xp_sheet[72]
xp_73 = xp_sheet[73]
xp_74 = xp_sheet[74]
xp_75 = xp_sheet[75]
xp_76 = xp_sheet[76]
xp_77 = xp_sheet[77]
xp_78 = xp_sheet[78]
xp_79 = xp_sheet[79]
xp_80 = xp_sheet[80]
xp_81 = xp_sheet[81]
xp_82 = xp_sheet[82]
xp_83 = xp_sheet[83]
xp_84 = xp_sheet[84]
xp_85 = xp_sheet[85]
xp_86 = xp_sheet[86]
xp_87 = xp_sheet[87]
xp_88 = xp_sheet[88]
xp_89 = xp_sheet[89]
xp_90 = xp_sheet[90]
xp_91 = xp_sheet[91]
xp_92 = xp_sheet[92]
xp_93 = xp_sheet[93]
xp_94 = xp_sheet[94]
xp_95 = xp_sheet[95]
xp_96 = xp_sheet[96]
xp_97 = xp_sheet[97]
xp_98 = xp_sheet[98]
xp_99 = xp_sheet[99]
xp_100 = xp_sheet[100]
